import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {execFileSync} from 'node:child_process';

const root=process.cwd(),freshnessMode=process.argv.includes('--freshness'),errors=[],warnings=[];
const requiredFiles=['index.html','certs.js','styles.css','professional.css','professional-components.css','learning-resources.css','roadmap-map.css','roadmap-zoom.css','weekly-coach.css','sw.js','manifest.json','src/cert-extensions.js','src/catalogue-currentness.js','src/catalogue-policy-normalize.js','src/path-defaults.js','src/config.js','src/learning-resources.js','src/learning-resources-normalize.js','src/state-core.js','src/renderer.js','src/dates.js','src/storage.js','src/personalization.js','src/validation.js','src/phase-engine.js','src/source-registry.js','src/source-registry-current.js','src/data-health.js','src/competency-engine.js','src/market-value.js','src/career-framework.js','src/capability-gates.js','src/recommendation-engine.js','src/filter-intelligence.js','src/topic-engine.js','src/planner.js','src/career-advisor.js','src/assessment-bank.js','src/career-mentor.js','src/weekly-coach.js','src/exports.js','src/notifications.js','src/sync.js','src/github-sync.js','src/ux.js','src/github-sync-ui.js','src/market-value-ui.js','src/intelligence-ui.js','src/career-ui.js','src/learning-path-ui.js','src/roadmap-zoom.js','src/roadmap-map-ui.js','src/roadmap-clickthrough.js','src/personalization-ui.js','src/workspace-shell.js','src/learning-resources-ui.js','src/career-advisor-ui.js','src/career-mentor-ui.js','src/weekly-coach-ui.js','src/accessibility.js','src/bootstrap.js','tests.html','tests.js','tools/filter-model-check.mjs','tools/privacy-check.mjs','tools/source-check.mjs'];
requiredFiles.push('src/curriculum-audit.js','tools/curriculum-audit-check.mjs');
for(const file of requiredFiles)if(!fs.existsSync(path.join(root,file)))errors.push(`Missing required file: ${file}`);
for(const retired of ['app.js','stability.js'])if(fs.existsSync(path.join(root,retired)))errors.push(`${retired} should remain retired.`);
const jsFiles=requiredFiles.filter(file=>/\.(?:js|mjs)$/.test(file)&&fs.existsSync(path.join(root,file)));for(const file of jsFiles){try{execFileSync(process.execPath,['--check',path.join(root,file)],{stdio:'pipe'});}catch(error){errors.push(`Syntax check failed: ${file}\n${error.stderr?.toString()||error.message}`);}}

let certs=[];try{const canonical=fs.readFileSync(path.join(root,'certs.js'),'utf8'),extensions=fs.readFileSync(path.join(root,'src/cert-extensions.js'),'utf8'),currentness=fs.readFileSync(path.join(root,'src/catalogue-currentness.js'),'utf8'),sandbox={console,Date,Math,JSON,Object,Array,Set,Map,String,Number,Boolean,RegExp,Intl,URL};vm.createContext(sandbox);vm.runInContext(`${canonical}\n${extensions}\n${currentness}\n;globalThis.__CERTS__=CERTS;`,sandbox,{filename:'cert-catalogue.js',timeout:5000});certs=sandbox.__CERTS__;if(!Array.isArray(certs))errors.push('CERTS did not evaluate to an array.');}catch(error){errors.push(`Unable to evaluate certification catalogue: ${error.message}`);}
let sourceRegistry={};try{const source=fs.readFileSync(path.join(root,'src/source-registry.js'),'utf8'),current=fs.readFileSync(path.join(root,'src/source-registry-current.js'),'utf8'),sandbox={window:{CertTrackerV3:{}},Object};vm.createContext(sandbox);vm.runInContext(`${source}\n${current}`,sandbox,{filename:'source-registry-bundle.js',timeout:1000});sourceRegistry=sandbox.window.CertTrackerV3.sourceRegistry||{};}catch(error){errors.push(`Unable to evaluate source registry: ${error.message}`);}
if(Array.isArray(certs)){
  const allowed=new Set(['CORE','FOUNDATION','CONDITIONAL','OPTIONAL','ROLE-DRIVEN','ARCHITECT','IDENTITY-SEC','POST-PLAN']),ids=new Set(),byId=new Map();
  for(const[index,cert]of certs.entries()){const label=cert?.id||`index ${index}`;if(!cert?.id)errors.push(`${label}: missing id`);else if(ids.has(cert.id))errors.push(`Duplicate id: ${cert.id}`);else{ids.add(cert.id);byId.set(cert.id,cert);}if(!cert?.name)errors.push(`${label}: missing name`);if(!Number.isInteger(cert?.phase)||cert.phase<1||cert.phase>6)errors.push(`${label}: invalid phase`);if(!allowed.has(cert?.track))errors.push(`${label}: invalid track ${cert?.track}`);if(!Array.isArray(cert?.deps))warnings.push(`${label}: deps is not an array`);if(!Array.isArray(cert?.hours)||cert.hours.length!==2||cert.hours.some(n=>!Number.isFinite(Number(n))))warnings.push(`${label}: invalid hours range`);if(!Number.isFinite(Number(cert?.roi))||Number(cert.roi)<0||Number(cert.roi)>10)warnings.push(`${label}: ROI should be 0-10`);if(cert?.cvValue!=null&&(!Number.isFinite(Number(cert.cvValue))||Number(cert.cvValue)<0))errors.push(`${label}: invalid career-value signal`);}
  for(const required of ['ccnp-enterprise','ccie-enterprise','ai-901','sc-500','isa-cap-associate','isa-cap','isa95-fund','bcs-arch-found','bcs-arch-solution','bcs-arch-security','fortinet-ot-security'])if(!ids.has(required))errors.push(`Structured-learning catalogue is missing ${required}.`);
  if(byId.get('ccie-enterprise')&&!byId.get('ccie-enterprise').deps?.includes('ccnp-enterprise'))errors.push('CCIE Enterprise must remain an explicit post-CCNP expert branch in the learning model.');
  for(const cert of certs)for(const dep of cert?.deps||[]){if(!ids.has(dep))errors.push(`${cert.id}: missing dependency ${dep}`);if(dep===cert.id)errors.push(`${cert.id}: self dependency`);}
  const visiting=new Set(),visited=new Set();function visit(id,trail=[]){if(visiting.has(id)){errors.push(`Dependency cycle: ${[...trail,id].join(' -> ')}`);return;}if(visited.has(id))return;visiting.add(id);for(const dep of byId.get(id)?.deps||[])visit(dep,[...trail,id]);visiting.delete(id);visited.add(id);}for(const id of ids)visit(id);
  for(const cert of certs.filter(c=>c.gateway)){const source=sourceRegistry[cert.id];if(!source||source.level!=='CERT'||!/^https:\/\//.test(source.url||''))errors.push(`${cert.id}: gateway requires audited cert-level HTTPS provenance`);}
  const core=certs.filter(c=>c.track==='CORE'),audited=core.filter(c=>sourceRegistry[c.id]?.level==='CERT');if(audited.length<core.length-1)errors.push(`Core provenance coverage too low: ${audited.length}/${core.length}`);
  const now=Date.now(),fresh={fresh:0,review:0,stale:0,unknown:0};for(const cert of certs){const verifiedAt=sourceRegistry[cert.id]?.verifiedAt||cert.verifiedAt;if(!verifiedAt){fresh.unknown++;continue;}const raw=/^\d{4}-\d{2}$/.test(verifiedAt)?`${verifiedAt}-15T12:00:00Z`:`${verifiedAt}T12:00:00Z`,age=(now-new Date(raw).getTime())/86400000;if(!Number.isFinite(age))fresh.unknown++;else if(age<=180)fresh.fresh++;else if(age<=365)fresh.review++;else fresh.stale++;}console.log(`Catalogue record dates only: ${certs.length} records — ${fresh.fresh} recent, ${fresh.review} review, ${fresh.stale} stale, ${fresh.unknown} unknown. This is not factual verification.`);if(freshnessMode&&(fresh.review||fresh.stale||fresh.unknown))console.log('Freshness review queue is non-empty.');

  try{
    const audit=fs.readFileSync(path.join(root,'src/curriculum-audit.js'),'utf8'),learning=fs.readFileSync(path.join(root,'src/learning-resources.js'),'utf8'),normalize=fs.readFileSync(path.join(root,'src/learning-resources-normalize.js'),'utf8');
    const sandbox={console,Date,Math,JSON,Object,Array,Set,Map,String,Number,Boolean,RegExp,Intl,URL,encodeURIComponent,CERTS:certs,window:{CertTrackerV3:{sourceRegistry,util:{clamp:(v,min,max)=>Math.min(max,Math.max(min,v))}}}};
    vm.createContext(sandbox);vm.runInContext(`${audit}\n${learning}\n${normalize}`,sandbox,{filename:'learning-resources-bundle.js',timeout:5000});
    const lr=sandbox.window.CertTrackerV3.learningResources;if(!lr?.validate?.())errors.push('Learning-resource coverage does not validate across the full certification catalogue.');
    else{for(const cert of certs){const p=lr.profile(cert);if(!p.subjects?.length)errors.push(`${cert.id}: no subject coverage generated`);if(!p.stack?.length||p.stack.length<3)errors.push(`${cert.id}: recommended learning stack has fewer than 3 links`);for(const subject of p.subjects||[]){if(subject.depth<1||subject.depth>5)errors.push(`${cert.id}: invalid depth for ${subject.topic}`);if(!subject.resources||subject.resources.length<3)errors.push(`${cert.id}: ${subject.topic} has fewer than 3 topic resources`);if(!(subject.resources||[]).some(row=>!/youtube\.com\/results|udemy\.com\/courses\/search/.test(row.url||'')))errors.push(`${cert.id}: ${subject.topic} has discovery searches but no direct source`);}}}
  }catch(error){errors.push(`Unable to validate learning-resource model: ${error.message}`);}
}

try{const pathDefaults=fs.readFileSync(path.join(root,'src/path-defaults.js'),'utf8');for(const id of ['ccnp-enterprise','ccie-enterprise','crowdstrike-ccfa','sc-500','ai-103'])if(!pathDefaults.includes(`'${id}'`))errors.push(`Default learning path does not expose ${id}.`);}catch(error){errors.push(`Unable to inspect default learning path: ${error.message}`);}
try{const renderer=fs.readFileSync(path.join(root,'src/renderer.js'),'utf8');if(/\bconst\s+state\s*=/.test(renderer)||/\bconst\s+SK\s*=/.test(renderer))errors.push('Renderer still owns application state.');if(/\b(?:c|cert)\.phase\s*=/.test(renderer)||renderer.includes('Object.entries(state.phaseOverrides).forEach'))errors.push('Renderer still mutates certification phases.');if(!renderer.includes('function certPhase(cert)'))errors.push('Renderer is not resolving effective phases through the state core.');}catch(error){errors.push(`Unable to inspect renderer: ${error.message}`);}
try{const intelligence=fs.readFileSync(path.join(root,'src/filter-intelligence.js'),'utf8');for(const marker of ['global.nextCoreCert=function','global.orderPhaseCerts=orderPhaseLearningFirst','goalForFilter','freshnessPenalty','pathBias'])if(!intelligence.includes(marker))errors.push(`Filter-wide learning intelligence is missing ${marker}.`);}catch(error){errors.push(`Unable to inspect filter intelligence: ${error.message}`);}
try{const roadmap=fs.readFileSync(path.join(root,'src/roadmap-map-ui.js'),'utf8');for(const marker of ['data-map-filter','data-map-jump-cert','ct-map-viewport','ct-map-stage','data-map-zoom-in','data-map-zoom-out','data-map-zoom-fit','data-map-zoom-reset','tutorAdvice','roleGateStatus','learningResources.profile'])if(!roadmap.includes(marker))errors.push(`Roadmap map is missing required capability: ${marker}`);}catch(error){errors.push(`Unable to inspect roadmap map: ${error.message}`);}
try{const roadmapCss=fs.readFileSync(path.join(root,'roadmap-map.css'),'utf8');for(const marker of ['overflow:auto','-webkit-overflow-scrolling:touch'])if(!roadmapCss.includes(marker))errors.push(`Roadmap map mobile panning is missing ${marker}.`);const zoomCss=fs.readFileSync(path.join(root,'roadmap-zoom.css'),'utf8');for(const marker of ['touch-action:none','ct-map-zoom-group','min-height:44px'])if(!zoomCss.includes(marker))errors.push(`Roadmap zoom CSS is missing ${marker}.`);const zoomJs=fs.readFileSync(path.join(root,'src/roadmap-zoom.js'),'utf8');for(const marker of ['pointerdown','pointermove','pointers.size===2','fitWidth','CertTrackerRoadmapZoom'])if(!zoomJs.includes(marker))errors.push(`Roadmap pinch/zoom engine is missing ${marker}.`);}catch(error){errors.push(`Unable to inspect roadmap zoom system: ${error.message}`);}
try{const index=fs.readFileSync(path.join(root,'index.html'),'utf8'),order=['certs.js','src/cert-extensions.js','src/catalogue-currentness.js','src/catalogue-policy-normalize.js','src/path-defaults.js','src/config.js','src/learning-resources.js','src/learning-resources-normalize.js','src/state-core.js','src/renderer.js','src/dates.js','src/storage.js','src/personalization.js','src/validation.js','src/phase-engine.js','src/source-registry.js','src/source-registry-current.js','src/data-health.js','src/competency-engine.js','src/market-value.js','src/career-framework.js','src/capability-gates.js','src/recommendation-engine.js','src/filter-intelligence.js','src/topic-engine.js','src/planner.js','src/career-advisor.js','src/assessment-bank.js','src/career-mentor.js','src/weekly-coach.js','src/exports.js','src/notifications.js','src/sync.js','src/github-sync.js','src/ux.js','src/github-sync-ui.js','src/market-value-ui.js','src/intelligence-ui.js','src/career-ui.js','src/learning-path-ui.js','src/roadmap-zoom.js','src/roadmap-map-ui.js','src/roadmap-clickthrough.js','src/personalization-ui.js','src/workspace-shell.js','src/learning-resources-ui.js','src/career-advisor-ui.js','src/career-mentor-ui.js','src/weekly-coach-ui.js','src/accessibility.js','src/bootstrap.js'];let last=-1;for(const file of order){const at=index.indexOf(file);if(at<0)errors.push(`index.html does not load ${file}`);else if(at<last)errors.push(`index.html loads ${file} out of order`);last=at;}for(const css of ['styles.css','professional.css','professional-components.css','learning-resources.css','roadmap-map.css','roadmap-zoom.css','weekly-coach.css'])if(index.indexOf(css)<0)errors.push(`index.html does not load ${css}`);if(/fonts\.googleapis\.com/i.test(index))errors.push('index.html still depends on Google Fonts.');}catch(error){errors.push(`Unable to validate index.html: ${error.message}`);}
try{const sw=fs.readFileSync(path.join(root,'sw.js'),'utf8'),pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8')),expected=`cert-tracker-assets-v${pkg.version}`;for(const file of ['professional.css','professional-components.css','learning-resources.css','roadmap-map.css','roadmap-zoom.css','weekly-coach.css','src/catalogue-currentness.js','src/learning-resources.js','src/learning-resources-normalize.js','src/state-core.js','src/storage.js','src/personalization.js','src/competency-engine.js','src/career-framework.js','src/capability-gates.js','src/recommendation-engine.js','src/filter-intelligence.js','src/topic-engine.js','src/planner.js','src/career-advisor.js','src/career-mentor.js','src/weekly-coach.js','src/intelligence-ui.js','src/career-ui.js','src/learning-path-ui.js','src/roadmap-zoom.js','src/roadmap-map-ui.js','src/roadmap-clickthrough.js','src/personalization-ui.js','src/workspace-shell.js','src/learning-resources-ui.js','src/weekly-coach-ui.js','src/accessibility.js'])if(!sw.includes(file))errors.push(`Service worker does not cache ${file}`);if(!sw.includes(expected))errors.push(`Service worker cache version is not current; expected ${expected}.`);if(sw.includes('app.js'))errors.push('Service worker still caches retired app.js.');}catch(error){errors.push(`Unable to validate sw.js: ${error.message}`);}
if(warnings.length){console.warn(`Warnings (${warnings.length}):`);warnings.slice(0,60).forEach(x=>console.warn(`- ${x}`));}if(errors.length){console.error(`Quality gate failed (${errors.length}):`);errors.forEach(x=>console.error(`- ${x}`));process.exit(1);}console.log('Cert Tracker quality gate passed.');
