// Cert Tracker — original, vendor-neutral knowledge checks for adaptive study evidence.
(function initAssessmentBank(global){
  'use strict';
  const CT=global.CertTrackerV3;if(!CT)throw new Error('config.js must load before assessment-bank.js');
  const q=(id,domain,difficulty,prompt,options,answer,rationale,keywords,certIds=[])=>Object.freeze({id,domain,difficulty,prompt,options:Object.freeze(options),answer,rationale,keywords:Object.freeze(keywords),certIds:Object.freeze(certIds)});
  const QUESTIONS=Object.freeze([
    q('net-arp-01','Networking',1,'A host needs to send an IPv4 packet to another host on the same subnet but has no cached layer-2 address. What should happen first?',['It broadcasts an ARP request for the destination IP','It asks the default gateway to perform DNS resolution','It sends the packet with an all-zero destination MAC','It starts a TCP handshake with the switch'],0,'ARP resolves a local IPv4 next-hop address to a link-layer address before the Ethernet frame can be addressed.',['arp','ethernet','layer 2','ipv4'],['network-plus','ccna']),
    q('net-gateway-01','Networking',1,'A workstation is sending to an IPv4 destination outside its local subnet. Which layer-2 destination does its first Ethernet frame normally use?',['The remote server MAC address','The default gateway MAC address','The DNS server MAC address','The broadcast MAC address'],1,'The IP destination remains the remote host, but the first local Ethernet hop is addressed to the default gateway.',['routing','default gateway','ethernet','ipv4'],['network-plus','ccna']),
    q('net-vlan-01','Switching',2,'Two access ports belong to different VLANs on the same switch. What is required for their attached hosts to exchange IP traffic?',['A larger MAC address table','A layer-3 device or switched virtual interfaces routing between the VLANs','PortFast on both access ports','A trunk between the two access ports'],1,'VLANs are separate layer-2 broadcast domains; communication between them requires layer-3 routing and an allowed policy.',['vlan','switching','inter-vlan','segmentation'],['ccna','ccnp-enterprise']),
    q('net-trunk-01','Switching',2,'A newly added VLAN works on one switch but not across an existing 802.1Q trunk. What is the most direct first configuration check?',['Whether the VLAN is allowed on the trunk at both ends','Whether every endpoint has a static ARP entry','Whether the access ports use full duplex','Whether DNS recursion is enabled'],0,'A VLAN omitted from either end of the trunk allow-list cannot traverse that link; verify state before making broader changes.',['vlan','trunk','802.1q','switching'],['ccna','ccnp-enterprise']),
    q('net-stp-01','Switching',2,'Why does spanning tree place some redundant switch links into a non-forwarding state?',['To prevent layer-2 loops while preserving a backup path','To encrypt traffic between switches','To increase the available VLAN ID range','To translate private addresses'],0,'Redundant layer-2 paths can cause broadcast storms and MAC-table instability; spanning tree maintains a loop-free forwarding topology.',['spanning tree','stp','switching','loop'],['ccna','ccnp-enterprise']),
    q('net-dhcp-01','Networking',2,'A client receives a DHCP offer but never completes address assignment. Which evidence best narrows whether the failure is at the client, relay, or server boundary?',['A packet capture showing the DHCP message sequence and source interfaces','A successful DNS lookup from another subnet','The switch model number','A continuous ping to 127.0.0.1'],0,'The discover/offer/request/ack sequence and relay information reveal where the exchange stops without guessing.',['dhcp','relay','packet capture','troubleshoot'],['network-plus','ccna']),
    q('net-dns-01','Networking',2,'Users can reach a service by IP address but not by hostname. Which first check provides the most discriminating evidence?',['Query the configured resolver and inspect the returned record or error','Replace the access switch','Disable the host firewall permanently','Increase the DHCP lease duration'],0,'A direct resolver query separates name-resolution failure from transport or application reachability.',['dns','name resolution','troubleshoot'],['network-plus','ccna']),
    q('net-tcp-01','Networking',2,'A capture shows repeated TCP SYN packets from a client and no SYN-ACK or RST. What can be concluded safely?',['The connection is not completing, but the capture alone does not prove which device drops the traffic','The server application has definitely crashed','DNS is definitely misconfigured','The client and server completed mutual TLS'],0,'The symptom establishes a missing response at the capture point; path, policy, return-route and listener evidence are still needed.',['tcp','packet capture','firewall','troubleshoot'],['network-plus','ccna']),
    q('net-route-01','Routing',2,'A router has two matching routes for a destination: /16 and /24. Assuming both are installed, which is selected?',['The /24 route because it is the longest prefix match','The /16 route because it covers more addresses','Both routes in round-robin order regardless of metric','The route learned most recently'],0,'Forwarding uses the most specific matching prefix before administrative distance or metric comparisons between equal prefixes.',['routing','longest prefix','subnetting'],['ccna','ccnp-enterprise']),
    q('net-ospf-01','Routing',3,'Two OSPF neighbours remain in a pre-adjacency state after a link change. Which comparison is most useful before resetting either router?',['Interface addressing, area, timers, network type and authentication on both ends','The DNS suffix search list','The users logged into each router','The browser proxy settings'],0,'Adjacency depends on compatible link and OSPF parameters; comparing observed state is safer than blind resets.',['ospf','routing','adjacency','troubleshoot'],['ccna','ccnp-enterprise']),
    q('sec-nat-01','Network security',2,'An outbound connection works, but an unsolicited inbound connection to a private host does not. Which distinction matters most?',['Source NAT state does not automatically create an inbound destination-NAT and policy rule','ARP can only resolve public addresses','TCP cannot traverse routers','Private hosts cannot use default gateways'],0,'Outbound state translation and inbound publishing are different controls; inbound access needs an explicit translation/listener and permitted policy.',['nat','firewall','port forwarding','policy'],['network-plus','ccna','security-plus']),
    q('sec-segment-01','Network security',3,'What is the strongest evidence that a new network segment enforces its intended trust boundary?',['A documented allow-list tested with permitted and denied flows, with logs at the enforcement point','A diagram showing different VLAN colours','A successful ping between every segment','A statement that the firewall is stateful'],0,'A trust boundary is proven by policy-specific positive and negative tests plus enforcement telemetry.',['segmentation','firewall','zero trust','validation'],['security-plus','ccna','ccnp-enterprise']),
    q('sec-tls-01','Security',2,'A browser reports a certificate name mismatch although the certificate is within its validity dates. What is the likely issue?',['The requested hostname is absent from the certificate subject alternative names','The TCP receive window is too small','The DNS TTL is too long','The server uses a private IPv4 address'],0,'TLS identity validation compares the requested hostname with certificate names; valid dates alone do not establish identity.',['tls','pki','certificate','https'],['security-plus','sc-300']),
    q('sec-logs-01','Security operations',2,'Which logging design best supports investigation across identity, endpoint and network systems?',['Centralised timestamped events with consistent identities, retention and protected access','Only local debug logs overwritten daily','Screenshots taken when an incident occurs','A shared text file editable by every administrator'],0,'Correlation needs reliable time, identifiers, retention and integrity across sources.',['logging','siem','telemetry','incident'],['security-plus','crowdstrike-ccfa']),
    q('id-least-01','Identity',1,'Which access decision best applies least privilege?',['Grant the smallest role needed for the task and review it when the task ends','Grant administrator access to avoid future tickets','Share a service account across the team','Disable audit logging for privileged actions'],0,'Least privilege limits permissions and duration to the justified need, with review and accountability.',['iam','least privilege','rbac','identity'],['security-plus','sc-300']),
    q('id-oidc-01','Identity',3,'In an OpenID Connect sign-in, what is the ID token primarily intended to convey to the client?',['Authenticated identity claims about the user','A permanent database password','A network route to the identity provider','A replacement for every API access token'],0,'OIDC adds an identity layer: the ID token communicates authentication claims to the client; API authorization normally uses access tokens.',['openid','oidc','oauth','identity'],['sc-300','az-104']),
    q('win-dns-01','Windows infrastructure',2,'Why is correct DNS configuration especially important to an Active Directory domain member?',['Domain service discovery relies on DNS records such as SRV records','DNS replaces Kerberos encryption','DNS assigns file permissions','DNS stores every user password'],0,'AD clients use DNS service records to locate domain controllers and services; using an unrelated resolver breaks discovery.',['active directory','windows','dns','domain controller'],['az-802','mcit']),
    q('win-gpo-01','Windows infrastructure',2,'A Group Policy setting is not applying to one computer. Which evidence-led first step is best?',['Generate resultant-set or policy-result data for that computer and user','Delete every policy and recreate it','Reinstall the operating system','Add the user to Domain Admins'],0,'Resultant policy data shows scope, filtering, precedence and processing errors before changes are made.',['group policy','gpo','windows','troubleshoot'],['az-802','mcit']),
    q('cloud-shared-01','Cloud',1,'Under a typical cloud shared-responsibility model, which responsibility normally remains with the customer?',['Configuring identities, data access and deployed workload settings','Guarding the provider data-centre perimeter','Replacing failed physical disks in provider racks','Maintaining the provider hypervisor'],0,'The provider secures underlying facilities and platform layers while customers retain responsibility for their identities, data and workload configuration.',['cloud','shared responsibility','azure','security'],['az-900','az-104']),
    q('cloud-ha-01','Cloud architecture',3,'A service must survive the loss of one availability zone. What evidence most directly supports that claim?',['Components span failure domains and a controlled zone-loss test meets the recovery objective','The service has a premium product name','All resources are in one large virtual machine','Backups completed once last year'],0,'Resilience claims require architecture across the named failure boundary and recovery testing against objectives.',['availability zone','high availability','recovery','architecture'],['az-104','az-305']),
    q('linux-perm-01','Linux',2,'A service process can read a configuration file interactively as an administrator but fails when started normally. What should be checked first?',['The service account identity, file permissions and security context','The monitor resolution','The DNS root hints','The keyboard layout'],0,'A daemon runs under its configured identity and context, not the interactive administrator; inspect effective access before broad changes.',['linux','permissions','service','troubleshoot'],['linux-plus']),
    q('api-retry-01','Software and APIs',3,'An automation calls an external API that intermittently returns 429. Which behaviour is safest?',['Bounded retries with backoff and jitter while respecting retry guidance','An infinite tight retry loop','Immediately log the API secret','Treat every 429 as a successful response'],0,'Rate limits require bounded, delayed retries and explicit failure handling; jitter reduces synchronized retry storms.',['api','python','automation','retry','429'],['pcep','pcap','pcpp1']),
    q('code-secret-01','Software security',2,'Where should production automation obtain an API secret?',['From an approved secret store or protected runtime injection','From a public source-code comment','From a filename committed to the repository','From an error message shown to users'],0,'Secrets should be managed outside source control with restricted access, rotation and auditable delivery.',['python','api','secret','security','automation'],['pcep','pcap','security-plus']),
    q('phys-vms-01','Physical security systems',2,'Video is visible live but retrieval repeatedly fails after several days. Which evidence best separates capacity, retention and recording-policy causes?',['Recorded bitrate, retention configuration, available storage and recording events over the affected period','The camera paint colour','The operator desktop wallpaper','The building postcode alone'],0,'Retention is a function of actual recording load, storage and policy; measured evidence distinguishes design shortage from configuration or recording failure.',['video','vms','storage','retention','camera'],['mcie','mcde','mcit']),
    q('phys-ha-01','Physical security systems',3,'A security-management design claims high availability. What makes the claim testable?',['Named failure scenarios, expected failover behaviour, recovery objectives and witnessed tests','Two identical logos on the diagram','A larger operator monitor','A promise that the server is enterprise grade'],0,'Availability is an outcome measured across defined failures and recovery targets, not a product label.',['vms','access control','high availability','failover','security system'],['mcie','mcde','arcules-csp']),
    q('arch-trade-01','Architecture',3,'What turns an architecture choice into a defensible decision record?',['Context, options, constraints, trade-offs, decision and consequences','Only the selected product name','A diagram with no assumptions','A list of every available technology'],0,'A decision is reviewable when alternatives and consequences are explicit and tied to constraints.',['architecture','trade-off','decision','design'],['az-305','ccie-enterprise']),
    q('ot-safe-01','Operational technology',3,'Before actively scanning an unfamiliar operational network, what is the most important first action?',['Obtain owner approval and assess process-safety and availability impact','Increase scan intensity to finish quickly','Disable monitoring alerts','Assume office-network procedures are safe'],0,'Active techniques can disrupt fragile or safety-relevant systems; authorization and impact assessment precede testing.',['ot','ics','scada','safety','assessment'],['secot-plus']),
    q('backup-restore-01','Resilience',2,'Which evidence best demonstrates that a backup control is effective?',['A timed restore test that verifies usable data and records recovery results','A successful backup job status alone','A storage invoice','A screenshot of the backup schedule'],0,'Backup completion does not prove recoverability; restoration against recovery objectives provides the meaningful evidence.',['backup','restore','recovery','resilience'],['a-plus','network-plus','az-104']),
    q('trouble-change-01','Operations',2,'A service failed immediately after a change. What is the safest first response when impact is high and rollback is known good?',['Preserve evidence, follow the approved rollback, then verify recovery','Make several unrelated changes simultaneously','Delete the logs to save space','Wait without observing service health'],0,'A controlled rollback limits impact while preserving evidence; verification confirms that the rollback actually restored service.',['troubleshoot','change','rollback','operations'],[])
  ]);
  function valid(question){return question&&typeof question.id==='string'&&question.options?.length===4&&Number.isInteger(question.answer)&&question.answer>=0&&question.answer<4&&question.rationale;}
  function validate(){const ids=new Set(),errors=[];for(const question of QUESTIONS){if(!valid(question))errors.push(`Invalid question: ${question?.id||'unknown'}`);if(ids.has(question.id))errors.push(`Duplicate question: ${question.id}`);ids.add(question.id);}return Object.freeze({ok:errors.length===0,errors:Object.freeze(errors)});}
  const norm=value=>String(value||'').toLowerCase().replace(/[^a-z0-9+#.]+/g,' ');
  function candidates(cert,subject){const context=norm([cert?.id,cert?.code,cert?.name,cert?.provider,subject?.topic,subject?.description,subject?.depthInfo?.description].join(' '));return QUESTIONS.map(question=>{let score=question.certIds.includes(cert?.id)?12:0;for(const keyword of question.keywords)if(context.includes(norm(keyword)))score+=3;return{question,score};}).filter(row=>row.score>0).sort((a,b)=>b.score-a.score||a.question.difficulty-b.question.difficulty||a.question.id.localeCompare(b.question.id));}
  function get(id){return QUESTIONS.find(question=>question.id===id)||null;}
  function pick(cert,subject,history={}){const rows=candidates(cert,subject);if(!rows.length)return null;rows.sort((a,b)=>{const ah=history[a.question.id]?.attempts||[],bh=history[b.question.id]?.attempts||[],aw=ah[0]?.correct===false?1:0,bw=bh[0]?.correct===false?1:0;return bw-aw||ah.length-bh.length||b.score-a.score||a.question.id.localeCompare(b.question.id);});return rows[0]?.question||null;}
  CT.assessmentBank=Object.freeze({QUESTIONS,get,pick,candidates,validate});
})(window);
