// Career opportunity taxonomy and transparent, browser-local comparisons.
(function(global){
  'use strict';
  const CT=global.CertTrackerV3;if(!CT?.careerFramework)return;
  const cyber='https://www.ukcybersecuritycouncil.org.uk/careers-in-cyber/cyber-career-framework';
  const ncs='https://nationalcareers.service.gov.uk/job-profiles/';
  const family=(label,skills,archetype,source,tasks)=>Object.freeze({label,skills:skills.split(' '),archetype,source,tasks});
  const FAMILIES=Object.freeze({
    infrastructure:family('Infrastructure & IT operations','windows enterpriseInfra linux resilience networking','cloudEngineering',ncs+'network-engineer',[['infra-ad-dns-pki','Troubleshoot identity, DNS and operating-system dependencies'],['infra-ha-dr','Test backup, recovery and service continuity'],['ops-change','Deliver a controlled infrastructure change with rollback']]),
    network:family('Networking & network security','networking routing firewall wireless hybridNetwork','cloudEngineering',ncs+'network-engineer',[['network-routed-topology','Build and validate a routed and switched network'],['network-breakfix','Diagnose a network fault from packet and device evidence'],['security-segmentation','Implement and test segmentation, firewall policy and remote access']]),
    cloud:family('Cloud & platform engineering','cloud azure aws automation iac containers linux','cloudEngineering',ncs+'network-engineer',[['cloud-hybrid-network','Build a resilient cloud workload and explain its network flows'],['automation-infrastructure','Version and test infrastructure automation'],['platform-operations','Operate monitoring, deployment, cost and recovery controls']]),
    defence:family('Security operations & investigation','soc siem incident threat vulnerability networking','securityOperations',cyber,[['security-monitoring','Investigate a realistic alert and produce a defensible timeline'],['detection-quality','Write and tune a detection with false-positive analysis'],['incident-recovery','Contain an incident and validate recovery']]),
    identity:family('Identity & access management','iam zeroTrust pki accessIdentity cloud','identitySecurity',cyber,[['cloud-identity-flow','Trace authentication, federation and authorisation end to end'],['identity-lifecycle','Implement joiner/mover/leaver and access review controls'],['identity-recovery','Test privileged-access controls and identity recovery']]),
    appsec:family('Application, product & AI security','automation python apiIntegration containers aiSecurity offensive','appPlatformSecurity',cyber,[['offensive-api','Threat-model and remediate an application or API weakness'],['appsec-pipeline','Implement tested pipeline, dependency and secrets controls'],['ai-security-governance','Assess data, model/API and software supply-chain risks']]),
    governance:family('Governance, risk & privacy','governance privacy architecture commercial','governanceRisk',cyber,[['risk-assurance','Produce an asset-based risk assessment with defensible controls'],['audit-evidence','Collect and challenge audit evidence against requirements'],['risk-stakeholders','Explain residual risk and obtain accountable decisions']]),
    physical:family('Physical-security systems','physical vms access networking enterpriseInfra apiIntegration','physicalSecurity',ncs+'network-engineer',[['physical-vms-breakfix','Troubleshoot device, VMS, server and network faults end to end'],['physical-interoperability','Integrate VMS/access-control events across systems'],['physical-access-architecture','Document a secure, supportable system design and acceptance test']]),
    industrial:family('OT, industrial & building systems','ot otEngineering industrialProtocols networking resilience physical','otSecurity',cyber,[['ot-protocols','Explain captured industrial-protocol traffic and process impact'],['ot-segmentation','Design and validate industrial zones and conduits'],['ot-risk-assessment','Assess OT risk without compromising safety or availability']]),
    offensive:family('Offensive security & research','offensive pentest vulnerability linux python networking','offensiveSecurity',cyber,[['offensive-ad-path','Demonstrate a scoped attack path in an authorised environment'],['offensive-lateral','Explain prevention, detection and containment for the attack'],['offensive-report','Deliver actionable findings and verify remediation']]),
    software:family('Software, automation & integration','python automation apiIntegration linux database','appPlatformSecurity',ncs+'software-developer',[['software-delivery','Deliver a tested, version-controlled application or automation'],['automation-api-integration','Handle API authentication, errors and structured data'],['software-support','Debug, document and support software used by someone else']]),
    data:family('Data & geospatial systems','data database python apiIntegration architecture','cloudEngineering',ncs+'data-analyst-statistician',[['data-quality','Validate data quality and explain transformations'],['data-delivery','Deliver a reproducible analysis, pipeline or GIS service'],['data-governance','Document access, retention and recovery for the data']]),
    customer:family('Customer-facing technical & commercial','commercial apiIntegration architecture networking cloud','commercialTechnical',ncs+'network-engineer',[['architecture-stakeholders','Run technical discovery and explain trade-offs'],['customer-delivery','Deliver a customer demonstration, adoption plan or implementation'],['commercial-outcomes','Document customer outcomes, constraints and commercial assumptions']]),
    leadership:family('Architecture, delivery & leadership','architecture leadership commercial governance resilience','architectureConsulting',cyber,[['architecture-hld-lld','Defend a requirements-led design or delivery plan'],['architecture-bom-tco','Explain cost, risk, lifecycle and prioritisation decisions'],['architecture-ownership','Own delivery outcomes and coordinate stakeholders']])
  });
  // IDs remain stable for existing saved filters. Stage sets an evidence target,
  // not a universal seniority rank or a claim about the entry level of every vacancy.
  const rows=[
    ['career-support','infrastructure','IT Support Engineer','Diagnose user and service incidents and document repeatable fixes','a-plus network-plus',1],
    ['career-systems','infrastructure','Systems Engineer','Operate servers, identity, storage and resilient services','az-802 server-plus az-104',2],
    ['career-linux','infrastructure','Linux Systems Administrator','Maintain Linux services, permissions, observability and recovery','linux-plus autoops-plus',2],
    ['career-m365','infrastructure','Microsoft 365 Engineer','Administer tenant services, endpoint integrations and identity','sc-300 sc-401 sc-900',2],
    ['career-network','network','Network Engineer','Configure and troubleshoot enterprise routing, switching and connectivity','network-plus ccna ccnp-enterprise',2],
    ['career-netsec','network','Network Security Engineer','Implement and operate firewall, VPN and segmentation controls','ccna pan-ngfw-eng nse-4 security-plus',2],
    ['career-wireless','network','Wireless Network Engineer','Survey, design and troubleshoot wireless coverage and capacity','ccna ccnp-enterprise',2],
    ['career-cloud','cloud','Cloud Engineer','Deploy and support secure, resilient cloud workloads','az-104 aws-saa gcp-ace',2],
    ['career-devops','cloud','DevOps Engineer','Build reliable delivery pipelines and infrastructure automation','terraform az-400 aws-dop autoops-plus',2],
    ['career-sre','cloud','Site Reliability Engineer','Engineer service reliability, observability and incident improvement','linux-plus terraform cka',2],
    ['career-platform','cloud','Platform Engineer','Provide reusable developer platforms and safe deployment paths','terraform cka az-400',2],
    ['career-soc','defence','SOC Analyst','Triage alerts, investigate activity and escalate with useful evidence','security-plus cysa-plus btl1 sc-200',1],
    ['career-security','defence','Cyber Security Engineer','Implement and support security controls across systems','security-plus cysa-plus sc-200',2],
    ['pv-a-cloudsoc','defence','SOC Analyst — cloud specialism','Investigate cloud, identity and workload telemetry','sc-200 cysa-plus aws-security-specialty',2],
    ['pv-c-detection','defence','Detection Engineer','Build, validate and maintain detections and telemetry pipelines','gcda splunk-scda btl2',2],
    ['pv-c-ir','defence','Incident Response Analyst','Scope incidents, preserve evidence and coordinate containment','gcih gcfa btl2',2],
    ['pv-a-ir','defence','Digital Forensics Analyst — cloud specialism','Reconstruct cloud incidents and document evidence limitations','gcfa aws-security-specialty sc-200',2],
    ['pv-c-cti','defence','Threat Intelligence Analyst','Turn adversary information into defensive decisions','cysa-plus mad security-plus',2],
    ['pv-b-insider','defence','Insider Risk Analyst','Investigate insider risk with proportionate technical and governance controls','gcfa sc-300 crisc',2],
    ['pv-b-cpsoc','defence','SOC Analyst — OT specialism','Investigate industrial telemetry with process-impact awareness','gicsp grid sc-200',2],
    ['career-vuln','defence','Vulnerability Management Analyst','Prioritise vulnerabilities and verify remediation with service owners','cysa-plus security-plus pentest-plus',2],
    ['pv-a-iam','identity','Identity & Access Management Engineer','Implement federation, lifecycle, access governance and authentication','sc-300 sc-900 security-plus',2],
    ['career-pam','identity','Privileged Access Management Engineer','Implement privileged-session, credential and least-privilege controls','sc-300 hashicorp-vault',2],
    ['pv-c-appsec','appsec','Application Security Engineer','Help developers prevent and remediate application vulnerabilities','bscp csslp oswe pcap',2],
    ['pv-a-devsecops','appsec','DevSecOps Engineer','Integrate effective security controls into software delivery','az-400 terraform hashicorp-vault cks',2],
    ['pv-a-ai','appsec','AI Security Engineer','Threat-model AI systems and validate data, model and runtime controls','secai-plus caisp gaips',2],
    ['pv-a-k8s','appsec','Platform Security Engineer — Kubernetes specialism','Secure cluster identities, workloads, networks and supply chains','cka kcsa cks',2],
    ['pv-top-platform','appsec','Security Platform Engineer','Build and automate shared security tooling and telemetry services','sc-200 terraform az-400',2],
    ['pv-a-data','appsec','Data Security Engineer','Protect data stores, encryption, access and lifecycle controls','sc-401 cdpse ccsp',2],
    ['pv-c-grc','governance','Governance, Risk & Compliance Analyst','Assess controls and track evidence-led risk treatment','cismp iso-27001-li crisc',1],
    ['career-auditor','governance','IT Auditor','Test technology controls and communicate supported audit findings','cisa iso-27001-li',2],
    ['pv-a-privacy','governance','Privacy Engineer','Translate privacy requirements into technical data-lifecycle controls','cdpse cipp-e cipm',2],
    ['career-privacy','governance','Privacy Analyst','Support privacy assessments, records and operational governance','cipp-e cipm',1],
    ['career-physical-support','physical','Physical Security Systems Support Engineer','Diagnose and support networked video and access-control systems','mcit acp network-plus',1],
    ['career-integration','physical','Security Systems Integration Engineer','Integrate video, access, identity and enterprise systems','mcie lcp genetec-sc-ent',2],
    ['career-physical-design','physical','Security Systems Design Engineer','Translate requirements into VMS/PACS design and acceptance criteria','mcde lcda asis-psp',2],
    ['pv-b-se','customer','Solutions Engineer — physical security','Discover needs and demonstrate integrated physical-security solutions','mcde acp lcp',2],
    ['pv-b-otics','industrial','OT Cyber Security Engineer','Secure industrial networks without compromising process operations','iec-62443-cfs gicsp grid',2],
    ['career-industrial-network','industrial','Industrial Network Engineer','Deliver resilient connectivity for industrial control systems','ccna isa95-fund iec-62443-cfs',2],
    ['pv-b-smartbuilding','industrial','Building Systems Integration Engineer','Integrate and secure building controls, IoT and enterprise networks','network-plus isa95-fund iec-62443-cfs',2],
    ['career-controls','industrial','Control Systems Engineer','Develop and validate PLC/HMI control logic with process and safety discipline','isa-cap-associate isa95-fund',2],
    ['pv-c-offensive','offensive','Penetration Tester','Test authorised systems and report actionable remediation','pnpt htb-cpts oscp',2],
    ['pv-c-redteam','offensive','Red Team Operator','Exercise adversary scenarios to evaluate organisational defences','crto osep oscp',3],
    ['pv-c-malware','offensive','Malware Analyst / Reverse Engineer','Analyse malicious code and derive useful defensive findings','grem osed linux-plus',3],
    ['pv-top-embed','offensive','Embedded Systems Security Engineer','Assess firmware, device protocols and hardware trust boundaries','linux-plus osed security-plus',3],
    ['pv-b-pentest','offensive','Physical Security Penetration Tester','Evaluate authorised physical intrusion and blended attack scenarios','asis-psp pentest-plus network-plus',2],
    ['career-python','software','Python Developer','Deliver maintainable Python applications, services and tests','pcep pcap pcpp1',2],
    ['career-automation','software','IT Automation Engineer','Automate operational tasks with safe failure handling and testing','autoops-plus pcap terraform',2],
    ['career-api','software','Integration Developer','Build and support reliable authenticated API and data integrations','pcap hashicorp-vault',2],
    ['career-test','software','Test Automation Engineer','Build repeatable tests and diagnose failures in delivery pipelines','pcap az-400',2],
    ['career-game','software','Game / XR Developer','Deliver an interactive prototype with performance and usability evidence','pcep pcap',2],
    ['career-data-analyst','data','Data Analyst','Answer business questions through reproducible analysis and visualisation','pcep pcap',1],
    ['career-data-engineer','data','Data Engineer','Build reliable data ingestion, transformation and quality controls','pcap az-104',2],
    ['career-gis','data','GIS Analyst','Analyse spatial data and communicate defensible geospatial results','arcgis-foundation arcgis-associate',1],
    ['career-gis-dev','data','Geospatial Developer','Build and support mapping applications and spatial APIs','arcgis-foundation pcap arcgis-py-api',2],
    ['career-gis-admin','data','GIS Platform Administrator','Operate GIS services, access, capacity and recovery','esri-ent-prof esri-system-design',2],
    ['pv-a-se','customer','Solutions Engineer — cloud security','Translate customer requirements into demonstrable cloud-security solutions','az-104 ccsp aws-saa',2],
    ['pv-c-se','customer','Solutions Engineer — cybersecurity','Discover requirements and demonstrate appropriate security solutions','security-plus pan-ngfw-eng crowdstrike-ccf',2],
    ['career-vendor-support','customer','Technical Support Engineer — vendor products','Resolve complex customer product incidents and feed back defects','network-plus security-plus acp',1],
    ['career-services','customer','Professional Services Consultant','Implement customer solutions and deliver a supportable handover','az-104 mcie prince2-prac',2],
    ['pv-top-tam','customer','Technical Account Manager','Own technical adoption, escalations and customer-success plans','itil-4-foundation az-104',2],
    ['pv-top-ae','customer','Enterprise Account Executive','Own qualification, commercial negotiation and a sales pipeline','meddic-found meddpicc-master',2],
    ['pv-b-consultancy','leadership','Security Consultant','Assess security needs and defend practical recommendations','cismp iso-27001-li cissp',2],
    ['pv-top-csa','leadership','Cloud Solutions Architect','Defend cloud designs across cost, resilience, identity and migration','az-305 aws-sap gcp-pca',3],
    ['career-security-architect','leadership','Security Architect','Own security design decisions and organisational control patterns','cissp issap sc-100',3],
    ['pv-top-pm','leadership','Security Product Manager','Prioritise product outcomes using customer, engineering and risk evidence','pragmatic-pmc pragmatic-pcpm',3],
    ['career-service-manager','leadership','IT Service Delivery Manager','Manage service outcomes, suppliers, incidents and improvement','itil-4-foundation prince2-prac',3],
    ['career-engineering-manager','leadership','Engineering Manager','Lead people, technical delivery and sustainable team performance','prince2-prac itil-4-foundation',3],
    ['pv-b-crisis','leadership','Business Continuity & Resilience Manager','Coordinate continuity, crisis exercises and validated recovery','crisc iso-27001-li prince2-prac',3],
    ['pv-top-ma','leadership','Cybersecurity Due Diligence Consultant','Assess technology risk and integration implications in transactions','cisa crisc cissp',3]
  ];
  const ROLES=Object.freeze(rows.map(([id,family,title,mission,certs,stage])=>Object.freeze({id,family,title,mission,certs:certs.split(' '),stage,source:family==='data'&&/GIS|Geospatial/.test(title)?'https://www.esriuk.com/en-gb/what-is-gis/careers':FAMILIES[family].source})));
  // Every career option has the same five-gate shape, but its credentials and
  // practical emphasis are selected for the family.  These are planning
  // ladders, not promises that an issuer or employer accepts a badge as a
  // substitute for experience.
  const PATHWAY_STAGE_META=Object.freeze([
    Object.freeze({key:'entry',label:'Entry / baseline',target:'Safe supervised contribution'}),
    Object.freeze({key:'foundation',label:'Foundation / operations',target:'Repeatable day-to-day delivery'}),
    Object.freeze({key:'practitioner',label:'Practitioner / ownership',target:'Independent bounded ownership'}),
    Object.freeze({key:'senior',label:'Senior / design',target:'Cross-system design and defence'}),
    Object.freeze({key:'endgame',label:'Endgame / leadership',target:'Strategic accountability and mentoring'})
  ]);
  const PATHWAY_TEMPLATES=Object.freeze({
    infrastructure:[['a-plus','network-plus'],['linux-plus','server-plus'],['az-802','az-104'],['sc-900','az-700'],['az-305','ccsp']],
    network:[['network-plus','security-plus'],['ccna','pan-practitioner'],['ccnp-enterprise','pan-netsec-pro'],['pan-ngfw-eng','pan-netsec-arch'],['ccie-enterprise','sc-100']],
    cloud:[['network-plus','az-900'],['az-104','aws-cloud-practitioner'],['terraform','az-700','aws-saa'],['az-400','sc-500'],['az-305','sc-100','ccsp']],
    defence:[['google-cyber','security-plus'],['cysa-plus','btl1'],['sc-200','mad','crowdstrike-ccfa'],['gcda','gcih','crowdstrike-ccf'],['gcfa','cissp','sc-100','ukcsc-princ']],
    identity:[['network-plus','security-plus'],['sc-900','az-104'],['sc-300','sc-401'],['sc-500','ccsp'],['sc-100','cissp','issap']],
    appsec:[['security-plus','pcep'],['secai-plus','pcap','bscp'],['terraform','az-400'],['csslp','cks'],['caisp','gaips','sc-100']],
    governance:[['google-cyber','security-plus'],['cismp','iso-27001-li'],['crisc','cisa'],['cissp','bcs-esa'],['ukcsc-princ','ukcsc-chart','csyp']],
    physical:[['a-plus','network-plus'],['mcit','acp','mcde'],['mcie','lcp'],['lce','lcda'],['asis-psp','bcs-esa','cissp']],
    industrial:[['network-plus','security-plus','iec-62443-cfs'],['secot-plus','isa95-fund'],['gicsp','iec-62443-cra'],['iec-62443-cds','iec-62443-cms','grid'],['iec-62443-expert','isa-cap','cissp']],
    offensive:[['network-plus','security-plus','linux-plus'],['thm-pt1','pentest-plus'],['pnpt','htb-cpts'],['oscp','crto'],['osed','osep','oswe','osee']],
    software:[['a-plus','network-plus','pcep'],['pcap','autoops-plus'],['terraform','az-400'],['pcpp1','cka'],['pcpp2','csslp','sc-100']],
    data:[['a-plus','network-plus','pcep'],['arcgis-foundation','pcap'],['az-104','arcgis-associate','esri-dev-found'],['arcgis-py-api','esri-ent-admin'],['esri-system-design','esri-ent-prof','ccsp']],
    customer:[['a-plus','network-plus'],['arcules-csp','acp','az-104','meddic-found'],['mcde','bcs-esa','itil-4-foundation'],['az-305','sc-500'],['cissp','meddpicc-master','ukcsc-princ']],
    leadership:[['network-plus','security-plus'],['itil-4-foundation','prince2-prac'],['cismp','bcs-esa','crisc'],['cissp','sc-100'],['issap','ukcsc-chart','csyp']]
  });
  // Role-level routes.  Family foundations are reused only where the capability
  // genuinely transfers; every role has its own sequence, specialism and
  // end-state evidence target.  This keeps the catalogue honest without
  // pretending that one family ladder fits seventy different jobs.
  const bespokeRoute=(stages,focus,capstone,transition)=>Object.freeze({
    stages:Object.freeze(stages.map((certs,index)=>Object.freeze({certs:Object.freeze(certs),focus,capstone,transition,index}))),
    focus,capstone,transition,bespoke:true
  });
  const ROLE_ROUTE_PROFILES=Object.freeze({
    'career-support':bespokeRoute([['a-plus','network-plus'],['server-plus','linux-plus'],['az-802','sc-900'],['az-104','itil-4-foundation'],['az-305','ccsp']],'endpoint triage, identity hand-offs and service recovery','own a support-to-engineering escalation with measured resolution and a reusable runbook','Systems Engineer or Microsoft 365 Engineer'),
    'career-systems':bespokeRoute([['a-plus','network-plus'],['server-plus','linux-plus'],['az-802','az-104'],['az-700','terraform'],['az-305','ccsp']],'hybrid Windows/Linux infrastructure, identity and resilience','design and operate a resilient service with tested recovery and change control','Cloud Engineer or Platform Engineer'),
    'career-linux':bespokeRoute([['a-plus','linux-plus'],['network-plus','server-plus'],['autoops-plus','terraform'],['az-104','cka'],['ccsp','cissp']],'Linux service operations, automation and observability','take ownership of a production-like Linux platform, including incident and recovery evidence','SRE or Platform Engineer'),
    'career-m365':bespokeRoute([['a-plus','network-plus'],['sc-900','sc-300'],['sc-401','az-104'],['sc-500','az-700'],['sc-100','ccsp']],'Microsoft 365 tenant, identity, endpoint and information protection','lead a tenant hardening or migration with adoption, rollback and audit evidence','Cloud Security Engineer or Security Architect'),
    'career-network':bespokeRoute([['network-plus','security-plus'],['ccna','pan-practitioner'],['ccnp-enterprise','pan-netsec-pro'],['pan-ngfw-eng','pan-netsec-arch'],['ccie-enterprise','sc-100']],'routing, switching, wireless dependencies and fault isolation','defend a multi-site network design and demonstrate recovery from a realistic outage','Network Security Engineer or Network Architect'),
    'career-netsec':bespokeRoute([['network-plus','security-plus'],['ccna','nse-4'],['pan-ngfw-eng','pan-secops-pro'],['pan-netsec-pro','pan-netsec-arch'],['sc-100','cissp']],'firewall policy, VPN, segmentation and secure traffic flows','design and validate a zero-trust network boundary with monitoring and rollback','Security Architect or Network Security Architect'),
    'career-wireless':bespokeRoute([['a-plus','network-plus'],['ccna','pan-practitioner'],['ccnp-enterprise','pan-netsec-analyst'],['pan-netsec-pro','pan-ngfw-eng'],['ccie-enterprise','pan-netsec-arch']],'RF fundamentals, enterprise WLAN design and secure roaming','survey and defend a wireless deployment with capacity, coverage and security acceptance evidence','Senior Network Engineer or Wireless Architect'),
    'career-cloud':bespokeRoute([['a-plus','network-plus'],['az-900','az-104'],['aws-saa','terraform'],['az-400','aws-security-specialty'],['az-305','ccsp']],'cloud landing zones, network flows, IaC and workload reliability','deliver a secure multi-service cloud migration with cost, recovery and validation evidence','Cloud Security Engineer or Cloud Solutions Architect'),
    'career-devops':bespokeRoute([['a-plus','network-plus'],['az-900','az-104'],['terraform','az-400'],['aws-dop','cks'],['az-305','ccsp']],'delivery pipelines, infrastructure as code and secure release controls','own a measurable delivery platform with rollback, supply-chain and reliability evidence','Platform Engineer or DevSecOps Engineer'),
    'career-sre':bespokeRoute([['a-plus','linux-plus'],['network-plus','server-plus'],['terraform','az-104'],['cka','az-400'],['aws-dop','ccsp']],'service-level objectives, observability, incident learning and resilient Linux platforms','run a game-day and prove improved availability, recovery time and operational learning','Principal SRE or Platform Architect'),
    'career-platform':bespokeRoute([['a-plus','network-plus'],['az-900','linux-plus'],['terraform','cka'],['az-400','cks'],['az-305','ccsp']],'internal developer platforms, golden paths and safe self-service','design a platform product with adoption measures, paved-road controls and recovery evidence','Platform Architect or Engineering Manager'),
    'career-soc':bespokeRoute([['google-cyber','security-plus'],['cysa-plus','btl1'],['sc-200','crowdstrike-ccfa'],['mad','gcih'],['btl2','cissp']],'alert triage, SIEM investigation and defensible escalation','own an investigation from alert to containment with a checked timeline and lessons learned','Detection Engineer or Incident Response Analyst'),
    'career-security':bespokeRoute([['security-plus','network-plus'],['cysa-plus','sc-200'],['crowdstrike-ccfa','sc-401'],['gcih','terraform'],['sc-100','cissp']],'control implementation across endpoints, identity, cloud and telemetry','lead a security-control rollout with measurable risk reduction and operational handover','Security Engineer (senior) or Security Architect'),
    'pv-a-cloudsoc':bespokeRoute([['security-plus','az-900'],['cysa-plus','sc-200'],['az-104','aws-security-specialty'],['crowdstrike-ccfa','sc-300'],['gcih','ccsp']],'cloud-native detections, identity telemetry and workload containment','investigate a cross-cloud incident and defend containment, evidence and recovery decisions','Cloud Detection Engineer or Cloud Security Engineer'),
    'pv-c-detection':bespokeRoute([['security-plus','google-cyber'],['cysa-plus','btl1'],['splunk-core-user','sc-200'],['splunk-scda','gcda'],['splunk-scde','btl2']],'detection-as-code, telemetry quality and false-positive reduction','ship a tested detection pack with coverage metrics, tuning history and response playbooks','Detection Engineering Lead or Security Platform Engineer'),
    'pv-c-ir':bespokeRoute([['security-plus','google-cyber'],['cysa-plus','btl1'],['sc-200','gcih'],['gcfa','btl2'],['cissp','sc-100']],'incident scoping, containment, evidence handling and recovery coordination','lead a post-incident review that proves evidence integrity and durable control improvements','Incident Response Lead or DFIR Consultant'),
    'pv-a-ir':bespokeRoute([['security-plus','az-900'],['cysa-plus','sc-200'],['gcfa','aws-security-specialty'],['gcih','ccsp'],['cissp','sc-100']],'cloud forensics, timeline reconstruction and evidence limitations','defend a cloud-forensics case file from acquisition through executive findings','Cloud DFIR Lead or Forensics Consultant'),
    'pv-c-cti':bespokeRoute([['google-cyber','security-plus'],['cysa-plus','mad'],['sc-200','btl1'],['gcih','gcda'],['cissp','btl2']],'adversary intelligence, analytic tradecraft and defensive decision support','turn a campaign assessment into prioritised detections, mitigations and stakeholder actions','Threat Intelligence Lead or CTI Manager'),
    'pv-b-insider':bespokeRoute([['security-plus','google-cyber'],['cysa-plus','sc-300'],['sc-401','sc-200'],['gcfa','crisc'],['cissp','sc-100']],'insider-risk investigations, access context and proportionate governance','run an insider-risk case with privacy safeguards, evidence review and accountable decisions','Insider Risk Lead or Security Governance Consultant'),
    'pv-b-cpsoc':bespokeRoute([['security-plus','secot-plus'],['gicsp','grid'],['sc-200','iec-62443-cfs'],['gcih','iec-62443-cra'],['cissp','iec-62443-cds']],'OT-aware SOC operations, process impact and safe escalation','investigate an OT alert without unsafe intervention and prove coordinated recovery','OT Detection Lead or OT Security Engineer'),
    'career-vuln':bespokeRoute([['security-plus','network-plus'],['cysa-plus','pentest-plus'],['sc-200','btl1'],['pnpt','crisc'],['cissp','sc-100']],'asset context, vulnerability prioritisation and remediation verification','run a risk-based remediation cycle with owner sign-off and retest evidence','Vulnerability Management Lead or Security Consultant'),
    'pv-a-iam':bespokeRoute([['security-plus','network-plus'],['sc-900','sc-300'],['az-104','sc-401'],['sc-500','hashicorp-vault'],['sc-100','ccsp']],'federation, lifecycle automation, access reviews and zero-trust identity','design and validate joiner/mover/leaver and privileged-access controls end to end','Identity Architect or IAM Lead'),
    'career-pam':bespokeRoute([['security-plus','network-plus'],['sc-900','sc-300'],['hashicorp-vault','sc-401'],['sc-500','ccsp'],['sc-100','cissp']],'privileged sessions, secrets management and least-privilege operating models','migrate a privileged workflow with break-glass, monitoring and recovery evidence','PAM Architect or Identity Security Lead'),
    'pv-c-appsec':bespokeRoute([['security-plus','pcep'],['pcap','bscp'],['pentest-plus','terraform'],['csslp','oswe'],['caisp','sc-100']],'secure SDLC, API threat modelling and developer enablement','embed tested security gates in a real delivery pipeline and verify remediation outcomes','Application Security Lead or Product Security Architect'),
    'pv-a-devsecops':bespokeRoute([['security-plus','pcep'],['pcap','az-400'],['terraform','hashicorp-vault'],['cks','csslp'],['sc-100','ccsp']],'security automation in CI/CD, supply-chain controls and developer feedback','own a secure delivery path with measurable lead-time, defect and recovery outcomes','DevSecOps Lead or Platform Security Architect'),
    'pv-a-ai':bespokeRoute([['security-plus','secai-plus'],['pcep','pcap'],['caisp','gaips'],['sc-401','ccsp'],['sc-100','aigp']],'AI threat modelling, data/model controls and responsible deployment','assure an AI-enabled service with abuse testing, data lineage and governance evidence','AI Security Architect or AI Risk Lead'),
    'pv-a-k8s':bespokeRoute([['security-plus','linux-plus'],['cka','kcsa'],['terraform','az-400'],['cks','hashicorp-vault'],['ccsp','sc-100']],'Kubernetes identity, runtime, network policy and supply-chain security','harden and operate a cluster platform with threat model, incident and upgrade evidence','Kubernetes Security Lead or Platform Security Architect'),
    'pv-top-platform':bespokeRoute([['security-plus','network-plus'],['sc-200','az-104'],['terraform','az-400'],['crowdstrike-ccfa','splunk-scda'],['sc-100','ccsp']],'shared security tooling, telemetry contracts and reliable automation','deliver a security platform product with adoption, SLO and control-efficacy evidence','Security Platform Architect or Engineering Manager'),
    'pv-a-data':bespokeRoute([['security-plus','sc-900'],['sc-401','sc-300'],['az-104','hashicorp-vault'],['ccsp','cdpse'],['sc-100','cissp']],'data classification, encryption, access and retention across cloud stores','design and validate a protected data flow with recovery, audit and privacy evidence','Data Security Architect or Privacy Engineering Lead'),
    'pv-c-grc':bespokeRoute([['google-cyber','security-plus'],['cismp','iso-27001-li'],['crisc','cisa'],['cissp','bcs-esa'],['ukcsc-princ','ukcsc-chart']],'control mapping, evidence quality and risk treatment tracking','own an auditable risk register with accountable residual-risk decisions','GRC Lead or Security Assurance Manager'),
    'career-auditor':bespokeRoute([['google-cyber','security-plus'],['cismp','iso-27001-li'],['cisa','crisc'],['cissp','bcs-esa'],['ukcsc-princ','ukcsc-chart']],'technology-control testing, sampling and clear supported findings','lead an end-to-end audit with defensible evidence, exceptions and remediation follow-up','IT Audit Manager or Assurance Consultant'),
    'pv-a-privacy':bespokeRoute([['security-plus','cipp-e'],['cipm','cdpse'],['sc-401','sc-300'],['crisc','iso-27001-li'],['cissp','aigp']],'privacy-by-design, data flows, retention and engineering controls','translate a DPIA into implemented controls and verify residual privacy risk','Privacy Engineering Lead or Data Protection Architect'),
    'career-privacy':bespokeRoute([['google-cyber','cipp-e'],['cipm','security-plus'],['cdpse','iso-27001-li'],['crisc','aigp'],['cissp','ukcsc-princ']],'operational privacy reviews, records and evidence-led advice','coordinate a privacy assessment through remediation and accountable sign-off','Privacy Engineer or Privacy Manager'),
    'career-physical-support':bespokeRoute([['a-plus','network-plus'],['mcit','acp'],['genetec-omnicast-tech','arcules-csp'],['mcie','lcp'],['mcde','asis-psp']],'VMS/PACS support, device networks and structured fault isolation','restore a multi-system security deployment and prove a supportable handover','Security Systems Integration Engineer'),
    'career-integration':bespokeRoute([['a-plus','network-plus'],['acp','mcit'],['mcie','genetec-sc-ent'],['lcp','lcda'],['mcde','lce']],'VMS, access control, APIs and enterprise interoperability','deliver and acceptance-test an integrated security solution with operational documentation','Integration Architect or Professional Services Consultant'),
    'career-physical-design':bespokeRoute([['a-plus','network-plus'],['mcit','acp'],['mcde','mcie'],['lcda','lcp'],['lce','asis-psp']],'security-system requirements, resilient design and acceptance engineering','defend a lifecycle-aware VMS/PACS design with bill of materials and test evidence','Physical Security Architect or Design Authority'),
    'pv-b-se':bespokeRoute([['a-plus','network-plus'],['acp','mcde'],['mcie','lcp'],['az-104','genetec-sc-ent'],['lce','asis-psp']],'customer discovery, physical-security architecture and demonstrable outcomes','lead a solution workshop through proof, design trade-offs and customer acceptance','Senior Solutions Engineer or Security Consultant'),
    'pv-b-otics':bespokeRoute([['network-plus','security-plus'],['secot-plus','iec-62443-cfs'],['gicsp','grid'],['iec-62443-cra','isa95-fund'],['iec-62443-cds','iec-62443-cms']],'OT asset visibility, zones/conduits and safe cyber-risk treatment','design an OT security improvement that preserves safety and availability','OT Security Architect or OT Programme Lead'),
    'career-industrial-network':bespokeRoute([['network-plus','ccna'],['isa95-fund','iec-62443-cfs'],['ccnp-enterprise','gicsp'],['grid','iec-62443-cra'],['iec-62443-cds','iec-62443-expert']],'industrial Ethernet, segmentation, protocols and deterministic resilience','commission a segmented industrial network with tested failover and operations handover','Industrial Network Architect or OT Security Engineer'),
    'pv-b-smartbuilding':bespokeRoute([['a-plus','network-plus'],['ccna','secot-plus'],['isa95-fund','iec-62443-cfs'],['gicsp','iec-62443-cra'],['grid','iec-62443-cds']],'building controls, IoT integration and converged network security','integrate building systems with safe segmentation, monitoring and acceptance evidence','Smart Building Security Architect'),
    'career-controls':bespokeRoute([['a-plus','network-plus'],['secot-plus','isa95-fund'],['iec-62443-cfs','gicsp'],['grid','iec-62443-cra'],['iec-62443-cds','isa-cap-associate']],'PLC/HMI fundamentals, process safety and controlled change','validate a control-system change with simulation, rollback and safety evidence','Control Systems Architect or OT Engineering Lead'),
    'pv-c-offensive':bespokeRoute([['network-plus','security-plus'],['thm-pt1','pentest-plus'],['pnpt','htb-cpts'],['oscp','crto'],['osep','oswe']],'scoped testing, exploit validation and remediation communication','lead a rules-of-engagement engagement and verify fixes without overclaiming impact','Senior Penetration Tester or Red Team Operator'),
    'pv-c-redteam':bespokeRoute([['network-plus','security-plus'],['thm-pt1','pentest-plus'],['crto','oscp'],['osep','htb-cpts'],['oswe','osed']],'adversary emulation, operational security and detection validation','plan and execute a bounded red-team exercise with blue-team learning outcomes','Red Team Lead or Adversary Simulation Manager'),
    'pv-c-malware':bespokeRoute([['a-plus','linux-plus'],['security-plus','thm-pt1'],['grem','gcfa'],['osed','oswe'],['osee','cissp']],'static/dynamic analysis, reverse engineering and defensive reporting','produce a defensible malware analysis with indicators, behaviour and mitigations','Reverse Engineering Lead or Malware Researcher'),
    'pv-top-embed':bespokeRoute([['a-plus','linux-plus'],['security-plus','network-plus'],['osed','grem'],['oswe','osee'],['oscp','cissp']],'firmware, embedded protocols and hardware trust boundaries','assess a device through firmware, interface and update-chain evidence','Embedded Security Architect or Product Security Lead'),
    'pv-b-pentest':bespokeRoute([['security-plus','network-plus'],['pentest-plus','asis-psp'],['pnpt','htb-cpts'],['oscp','crto'],['osep','cissp']],'authorised physical intrusion, social engineering boundaries and blended attack paths','deliver a safe physical assessment with evidence handling and verified remediation','Physical Security Test Lead or Security Consultant'),
    'career-python':bespokeRoute([['a-plus','pcep'],['pcap','network-plus'],['pcpp1','autoops-plus'],['pcpp2','terraform'],['az-400','csslp']],'maintainable Python, tests, APIs and production collaboration','ship a versioned Python service with tests, observability and a support handover','Senior Python Engineer or Automation Architect'),
    'career-automation':bespokeRoute([['a-plus','pcep'],['pcap','network-plus'],['autoops-plus','pcpp1'],['terraform','az-400'],['pcpp2','ccsp']],'safe operational automation, idempotency and failure handling','automate a high-value workflow with approval, rollback and measured toil reduction','Automation Lead or Platform Engineer'),
    'career-api':bespokeRoute([['a-plus','pcep'],['pcap','network-plus'],['hashicorp-vault','autoops-plus'],['terraform','az-400'],['pcpp2','csslp']],'authenticated APIs, contracts, errors and integration observability','own an integration from contract through production support and recovery','Integration Architect or API Platform Lead'),
    'career-test':bespokeRoute([['a-plus','pcep'],['pcap','network-plus'],['autoops-plus','az-400'],['terraform','pcpp1'],['pcpp2','csslp']],'test strategy, automation reliability and delivery feedback loops','build a maintainable test estate with failure triage and release-quality evidence','Test Automation Lead or Quality Engineering Manager'),
    'career-game':bespokeRoute([['a-plus','pcep'],['pcap','network-plus'],['pcpp1','autoops-plus'],['pcpp2','terraform'],['csslp','az-400']],'interactive software delivery, performance and secure user data','release an interactive product slice with telemetry, accessibility and support evidence','Senior Software Engineer or Technical Director'),
    'career-data-analyst':bespokeRoute([['a-plus','pcep'],['pcap','network-plus'],['arcgis-foundation','pcpp1'],['pcpp2','az-104'],['ccsp','cdpse']],'reproducible analysis, visualisation and data-quality reasoning','deliver a decision-ready analysis with lineage, limitations and stakeholder sign-off','Senior Data Analyst or Analytics Engineer'),
    'career-data-engineer':bespokeRoute([['a-plus','pcep'],['network-plus','pcap'],['az-104','terraform'],['pcpp1','arcgis-foundation'],['pcpp2','ccsp']],'reliable ingestion, transformations, quality and platform operations','operate a recoverable data pipeline with SLAs, quality checks and lineage','Data Platform Engineer or Data Architect'),
    'career-gis':bespokeRoute([['a-plus','arcgis-foundation'],['network-plus','arcgis-associate'],['arcgis-pro-pro','arcgis-utility-net'],['esri-geodata-prof','esri-online-admin'],['esri-ent-prof','esri-system-design']],'spatial analysis, cartographic communication and evidence quality','publish a defensible spatial analysis with reproducible methods and caveats','Senior GIS Analyst or Geospatial Consultant'),
    'career-gis-dev':bespokeRoute([['a-plus','arcgis-foundation'],['pcep','pcap'],['arcgis-py-api','esri-dev-found'],['arcgis-associate','arcgis-pro-pro'],['esri-system-design','esri-ent-prof']],'geospatial applications, spatial APIs and secure deployment','deliver a tested mapping service with API contracts, performance and support evidence','Geospatial Software Architect'),
    'career-gis-admin':bespokeRoute([['a-plus','arcgis-foundation'],['network-plus','esri-online-admin'],['esri-ent-admin','arcgis-associate'],['arcgis-utility-net','esri-geodata-prof'],['esri-system-design','esri-ent-prof']],'GIS service operations, access, capacity and recovery','design and operate a GIS platform with availability, backup and governance evidence','GIS Platform Architect or Geospatial Operations Lead'),
    'pv-a-se':bespokeRoute([['a-plus','network-plus'],['az-900','az-104'],['aws-saa','security-plus'],['ccsp','aws-security-specialty'],['az-305','sc-100']],'cloud-security discovery, architecture trade-offs and demonstrable controls','lead a customer proof through design, risk, cost and acceptance evidence','Cloud Security Architect or Principal Solutions Engineer'),
    'pv-c-se':bespokeRoute([['a-plus','network-plus'],['security-plus','cysa-plus'],['pan-practitioner','crowdstrike-ccf'],['pan-ngfw-eng','crowdstrike-ccfa'],['ccsp','cissp']],'cybersecurity discovery, product fit and outcome-led demonstrations','shape a multi-control solution with validated outcomes and honest limitations','Principal Cybersecurity Solutions Engineer'),
    'career-vendor-support':bespokeRoute([['a-plus','network-plus'],['security-plus','acp'],['ccna','crowdstrike-ccf'],['mcie','crowdstrike-ccfa'],['itil-4-foundation','ccsp']],'complex product support, reproducible diagnosis and escalation quality','own a critical customer issue through evidence, workaround and permanent fix','Senior Support Engineer or Technical Account Manager'),
    'career-services':bespokeRoute([['a-plus','network-plus'],['az-900','az-104'],['mcie','acp'],['az-400','prince2-prac'],['az-305','ccsp']],'implementation planning, technical handover and customer adoption','deliver a scoped implementation with acceptance, rollback and operational ownership','Professional Services Lead or Solutions Architect'),
    'pv-top-tam':bespokeRoute([['a-plus','network-plus'],['itil-4-foundation','az-900'],['az-104','sc-900'],['az-305','ccsp'],['itil-4-mp','cissp']],'service health, adoption, escalations and outcome planning','run a strategic account plan with measurable risk, adoption and renewal outcomes','Strategic Technical Account Director'),
    'pv-top-ae':bespokeRoute([['a-plus','network-plus'],['meddic-found','security-plus'],['meddpicc-master','az-900'],['pragmatic-pmc','ccsp'],['pragmatic-pcpm','cissp']],'technical qualification, value articulation and complex security buying','lead a multi-stakeholder enterprise cycle with evidence-based value and handover','Enterprise Sales Director or Security GTM Leader'),
    'pv-b-consultancy':bespokeRoute([['security-plus','network-plus'],['cismp','iso-27001-li'],['crisc','cisa'],['cissp','bcs-esa'],['ukcsc-princ','ukcsc-chart']],'risk-led security advice, evidence quality and practical adoption','deliver a defensible advisory engagement from discovery to verified improvement','Principal Security Consultant or Advisory Practice Lead'),
    'pv-top-csa':bespokeRoute([['network-plus','security-plus'],['az-900','az-104'],['aws-saa','terraform'],['az-305','aws-sap'],['sc-100','ccsp']],'multi-cloud architecture, migration, resilience and cost governance','own a board-defensible cloud architecture and transition roadmap','Principal Cloud Architect or Cloud Practice Lead'),
    'career-security-architect':bespokeRoute([['network-plus','security-plus'],['sc-900','sc-300'],['sc-200','sc-401'],['cissp','sc-100'],['issap','sabsa-found']],'enterprise security principles, control patterns and design assurance','set architecture guardrails and defend a measurable risk-reduction portfolio','Chief Security Architect or Security Design Authority'),
    'pv-top-pm':bespokeRoute([['a-plus','network-plus'],['security-plus','pragmatic-pmc'],['az-900','itil-4-foundation'],['pragmatic-pcpm','cissp'],['sc-100','ukcsc-princ']],'security product discovery, prioritisation and outcome measurement','own a security product strategy tied to customer evidence, risk and delivery reality','Group Product Manager or Product Director'),
    'career-service-manager':bespokeRoute([['a-plus','network-plus'],['itil-4-foundation','prince2-prac'],['az-104','security-plus'],['itil-4-mp','crisc'],['cism','cissp']],'service ownership, supplier governance, incident learning and improvement','run a service portfolio with measurable reliability, risk and customer outcomes','Head of Service Delivery or IT Operations Director'),
    'career-engineering-manager':bespokeRoute([['a-plus','network-plus'],['security-plus','itil-4-foundation'],['az-104','prince2-prac'],['cissp','crisc'],['cism','ukcsc-chart']],'technical leadership, delivery health and sustainable team systems','lead a team through a measurable delivery and capability improvement cycle','Engineering Director or Head of Engineering'),
    'pv-b-crisis':bespokeRoute([['security-plus','google-cyber'],['itil-4-foundation','prince2-prac'],['crisc','iso-27001-li'],['cism','cissp'],['ukcsc-chart','csyp']],'continuity planning, crisis exercises and validated recovery','coordinate a cross-functional exercise with tested recovery objectives and lessons','Resilience Director or Chief Risk Officer'),
    'pv-top-ma':bespokeRoute([['security-plus','google-cyber'],['cysa-plus','cisa'],['crisc','iso-27001-li'],['cissp','cism'],['issap','ukcsc-chart']],'cyber due diligence, evidence challenge and transaction integration risk','lead a technology-risk assessment that survives scrutiny through close and integration','Partner or Managing Director, Cyber Due Diligence')
  });
  const PATHWAY_CACHE=new Map(),CERT_BY_ID=new Map((typeof CERTS!=='undefined'?CERTS:[]).map(cert=>[cert.id,cert]));
  const CONTEXTS=Object.freeze({'pv-b-cni':'Sector: Critical national infrastructure','pv-top-finsec':'Sector: Financial services','pv-top-cleared':'Eligibility: Security-cleared work','pv-top-contractor':'Work model: Contracting'});
  const LEVELS=Object.freeze({UNKNOWN:0,NONE:0,LAB:25,USED:55,DESIGNED:80,OWNED:100});
  const byId=id=>ROLES.find(r=>r.id===id);
  const stageIndexForRole=role=>role.stage===1?0:role.stage===2?2:role.stage>=3?3:1;
  function orderCertIds(ids){
    const unique=[...new Set(ids)].filter(id=>CERT_BY_ID.has(id)),pending=new Set(unique),ordered=[];
    while(pending.size){
      const next=[...pending].find(id=>{
        const deps=CERT_BY_ID.get(id)?.deps||[];
        return deps.every(dep=>!pending.has(dep));
      })||[...pending][0];
      pending.delete(next);ordered.push(next);
    }
    return ordered.sort((a,b)=>{
      const pa=Number(CERT_BY_ID.get(a)?.phase)||0,pb=Number(CERT_BY_ID.get(b)?.phase)||0;
      return pa-pb||ordered.indexOf(a)-ordered.indexOf(b);
    });
  }
  function pathway(roleOrId){
    const role=typeof roleOrId==='string'?byId(roleOrId):roleOrId;
    if(!role)return null;
    if(PATHWAY_CACHE.has(role.id))return PATHWAY_CACHE.get(role.id);
    const family=FAMILIES[role.family],profile=ROLE_ROUTE_PROFILES[role.id];
    // No family fallback: a missing profile is a data error caught by the audit.
    const rawBuckets=(profile?.stages||PATHWAY_TEMPLATES.infrastructure.map(ids=>({certs:ids}))).map(stage=>[...(stage.certs||stage)]);
    const isAvailable=id=>{const cert=CERT_BY_ID.get(id),status=CT.sourceRegistry?.[id]?.credentialStatus;return !!cert&&(CT.credentials?.availability?CT.credentials.availability(cert).eligible:!['RETIRED','IN_DEVELOPMENT','UNCONFIRMED'].includes(status));};
    // Retired, unreleased and unconfirmed credentials may remain in the catalogue
    // for historical records, but they are not active pathway recommendations.
    const watchlist=Object.freeze([...new Set(rawBuckets.flat().filter(id=>CERT_BY_ID.has(id)&&!isAvailable(id)))].map(id=>Object.freeze({id,name:CERT_BY_ID.get(id).name||id,status:CT.sourceRegistry?.[id]?.credentialStatus||'UNAVAILABLE'})));
    const buckets=rawBuckets.map(ids=>ids.filter(isAvailable));
    const roleBucket=stageIndexForRole(role);
    for(const id of role.certs||[])if(isAvailable(id)&&!buckets.some(bucket=>bucket.includes(id)))buckets[roleBucket].push(id);
    const focus=family.label.toLowerCase(),tasks=family.tasks||[];
    const stages=PATHWAY_STAGE_META.map((meta,index)=>{
      const certIds=Object.freeze(orderCertIds(buckets[index]));
      const certifications=Object.freeze(certIds.map(id=>{const cert=CERT_BY_ID.get(id);return Object.freeze({id,name:cert.name||id,code:cert.code||'',phase:cert.phase||null,studyMaterials:cert.studyMaterials||'',subjects:Object.freeze([...(cert.subjects||[])])});}));
      const task=tasks[Math.min(Math.max(index-1,0),tasks.length-1)]?.[1]||`deliver reliable ${focus} work`;
      const roleFocus=profile?.focus||focus,capstone=profile?.capstone||`demonstrate ${role.mission.toLowerCase()}`,transition=profile?.transition||'the next role in this pathway';
      const objective=index===0?`Build safe vocabulary and baseline habits for ${roleFocus}.`:index===1?`Turn the baseline into repeatable ${roleFocus} operations.`:index===2?`Take independent ownership of bounded ${roleFocus} work.`:index===3?`Design and defend cross-system ${roleFocus} outcomes for ${role.title}.`:`Lead strategy, governance and mentoring around ${role.title}.`;
      const practice=index===0?`Use a supervised lab to explain the concepts behind “${role.mission}” and where these credentials apply.`:index===1?`Practise ${task.toLowerCase()} for ${roleFocus} with runbooks, rollback steps and peer review.`:index===2?`Own ${task.toLowerCase()} in the ${roleFocus} context and record the decision, test evidence and outcome.`:index===3?`Deliver ${task.toLowerCase()} across the systems relevant to ${roleFocus} and defend the trade-offs.`:`Create a portfolio around ${capstone}, mentor another operator and review the control or service outcome.`;
      const evidence=index===0?`A checked lab log explaining the ${roleFocus} data flows, risks and escalation points.`:index===1?`A repeatable ${roleFocus} runbook, fault-injection exercise and recovery record.`:index===2?`A real or representative ${roleFocus} change with before/after evidence, review notes and a clear rollback.`:index===3?`A defended ${roleFocus} design or migration pack with assumptions, validation, monitoring and acceptance criteria.`:`Accountable outcomes for ${capstone}, measured improvement, decision records and evidence that another person can operate the result.`;
      const exit=index===0?`Can contribute safely under supervision to ${roleFocus}.`:index===1?`Can deliver routine ${roleFocus} work consistently and explain failures.`:index===2?`Can own a bounded ${roleFocus} outcome from requirement through validation.`:index===3?`Can defend architecture and coordinate dependencies for ${role.title}.`:`Can set direction, coach others and remain accountable for ${role.title}-level outcomes.`;
      const relevance=index===0?`These credentials establish the shared baseline needed to enter ${roleFocus}; they are not a substitute for supervised practice.`:index===1?`This combination is the role’s operational core: use it to build repeatable ${roleFocus} habits and test failure recovery.`:index===2?`These specialist credentials deepen the decisions ${role.title} makes independently, so pair them with owned evidence.`:index===3?`This design tier is relevant when you can integrate ${roleFocus} across systems and defend risk, cost and lifecycle trade-offs.`:`The endgame credentials support strategic accountability in ${role.title}; validate the target vacancy, issuer rules and leadership scope before committing.`;
      const studyMaterials=Object.freeze(certifications.map(cert=>{const source=CERT_BY_ID.get(cert.id),learning=CT.learningResources.profile(source);return Object.freeze({id:cert.id,name:cert.name,materials:cert.studyMaterials,subjects:learning.subjects,resources:learning.stack,integrity:learning.integrity});}));
      const curriculum=Object.freeze({sequence:Object.freeze(['Learn the mapped outcomes in order','Build the smallest safe representative lab','Test retrieval and diagnose one controlled failure','Use the mapped tutor trigger only where independent work stalls','Produce the stage evidence and defend it before progressing']),subjects:studyMaterials.reduce((n,item)=>n+item.subjects.length,0),tutorCheckpoints:studyMaterials.reduce((n,item)=>n+item.integrity.tutorCheckpoints,0),reviewedResources:studyMaterials.reduce((n,item)=>n+item.integrity.reviewed,0),externalCandidates:studyMaterials.reduce((n,item)=>n+item.integrity.substantive,0)});
      return Object.freeze({...meta,certIds,certifications,studyMaterials,curriculum,objective,practice,evidence,exit,relevance,plan:Object.freeze({objective,practice,evidence,exit,relevance,studyMaterials,curriculum})});
    });
    const certIds=Object.freeze([...new Set(stages.flatMap(stage=>stage.certIds))]);
    const result=Object.freeze({roleId:role.id,roleTitle:role.title,family:role.family,bespoke:Boolean(profile?.bespoke),specialism:profile?.focus||focus,capstone:profile?.capstone||role.mission,transition:profile?.transition||'Compare the next rung against current vacancies',stages:Object.freeze(stages),certIds,certifications:Object.freeze(certIds.map(id=>{const cert=CERT_BY_ID.get(id);return Object.freeze({id,name:cert.name||id,code:cert.code||'',phase:cert.phase||null,studyMaterials:cert.studyMaterials||'',subjects:Object.freeze([...(cert.subjects||[])])});})),watchlist,totalCerts:certIds.length,plan:Object.freeze({sequence:'Complete one stage at a time; do not treat a certification as proof of readiness.',gate:'Only progress after the practical evidence and a current vacancy/issuer check support the next rung.',focus:`${role.title}: ${role.mission}`,capstone:profile?.capstone||role.mission,transition:profile?.transition||'Compare the next rung against current vacancies'})});
    PATHWAY_CACHE.set(role.id,result);return result;
  }
  function pathways(){return ROLES.map(pathway);}
  function pathwayAudit(){
    const missing=[];
    for(const role of ROLES){const p=pathway(role);if(!p.bespoke||p.stages.length!==PATHWAY_STAGE_META.length||p.stages.some(stage=>!stage.certIds.length||!stage.objective||!stage.practice||!stage.evidence||!stage.exit||!stage.relevance))missing.push(role.id);}
    return {roles:ROLES.length,stages:PATHWAY_STAGE_META.length,bespoke:ROLES.filter(role=>ROLE_ROUTE_PROFILES[role.id]?.bespoke).length,complete:missing.length===0,missing,minCertifications:Math.min(...ROLES.map(role=>pathway(role).totalCerts))};
  }
  function prefs(){const p=state.customization?.careerOptions;return p&&typeof p==='object'?p:{};}
  function update(patch){const next={...prefs(),...patch};const validation=CT.storage?.validateBackup({version:CT.version.backup,customization:{careerOptions:next}});if(validation&&!validation.ok)throw new Error(validation.errors.join(' '));CT.storage?.captureUndoPoint('career preferences');state.customization={...state.customization,careerOptions:{...prefs(),...patch}};if(patch.evidence&&CT.storage){for(const [id,level]of Object.entries(patch.evidence)){if(level==='UNKNOWN')delete state.capabilityEvidence[id];else state.capabilityEvidence[id]={...state.capabilityEvidence[id],level,updatedAt:new Date().toISOString()};}CT.storage.persistAll();}else save.customization();CT.events.emit('career-options-changed',{});CT.events.emit('state-saved',{key:'customization',at:new Date().toISOString()});}
  function requirements(role){return [...FAMILIES[role.family].tasks.map(([id,label])=>({id,label})),{id:`role:${role.id}`,label:role.mission}].map(r=>({...r,target:role.stage===1?'LAB':role.stage===3?'DESIGNED':'USED'}));}
  function evidenceLevel(id,p=prefs()){const shared=state.capabilityEvidence?.[id]?.level;const own=p.evidence?.[id];return Object.hasOwn(LEVELS,shared)?shared:Object.hasOwn(LEVELS,own)?own:'UNKNOWN';}
  function assess(role,p=prefs()){
    const f=FAMILIES[role.family],background=byId(p.background),ctx=CT.careerFramework.context();
    const weights=background?Object.fromEntries(FAMILIES[background.family].skills.map(k=>[k,1])):CT.careerFramework.ROLE_PROFILES[ctx.current]?.weights||{};
    const overlap=Math.round(f.skills.reduce((s,k)=>s+Math.min(1,weights[k]||0),0)/f.skills.length*100);
    const certs=role.certs.map(id=>CERTS.find(c=>c.id===id)).filter(Boolean),passed=certs.filter(c=>CT.credentials?CT.credentials.active(c):state.passes?.[c.id]),credential=certs.length?Math.round(passed.length/certs.length*100):0;
    const vote=p.interests?.[role.id]??p.families?.[role.family],interest=[0,50,100].includes(vote)?vote:null;
    const compatibility=Math.round(interest===null?overlap*.75+credential*.25:overlap*.6+credential*.2+interest*.2);
    const req=requirements(role).map(r=>{const level=evidenceLevel(r.id,p);return {...r,level,coverage:Math.min(100,LEVELS[level]/LEVELS[r.target]*100)};});
    const recorded=req.filter(r=>r.level!=='UNKNOWN').length,readiness=recorded?Math.round(req.reduce((s,r)=>s+r.coverage*(r.id.startsWith('role:')?.5:1/6),0)):null;
    const gaps=req.filter(r=>r.coverage<100),status=p.eligibility?.[role.id]==='ineligible'?'Eligibility barrier':!recorded?'Not assessed':!gaps.length?'Compare vacancies':readiness>=60?'Close evidence gaps':readiness>=25?'Build next':'Explore / build evidence';
    return {role,overlap,credential,interest,compatibility,provisional:interest===null,readiness,recorded,requirements:req,gaps,status,passed:passed.length,totalCerts:certs.length,shortlisted:!!p.shortlist?.[role.id],background:background?.title||CT.careerFramework.ROLE_PROFILES[ctx.current]?.label||'Unspecified'};
  }
  const normal=value=>String(value||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
  const ALIASES={'career-gis':['gis analyst','geospatial analyst','geographic information systems analyst'],'pv-a-iam':['iam engineer','identity engineer','identity and access management engineer'],'career-support':['it support engineer','systems support engineer','technical support engineer'],'pv-c-se':['cybersecurity engineer','cyber security engineer']};
  function matchesTitle(role,value){const text=' '+normal(value)+' ';return [role.title,...(ALIASES[role.id]||[])].some(alias=>{const tokens=normal(alias).split(' ').filter(x=>!['and','the'].includes(x));return tokens.every(token=>text.includes(' '+token+' '));});}
  function market(role,feed,now=Date.now()){
    const age=now-Date.parse(feed?.lastSuccessfulFetchAt||feed?.fetchedAt),fresh=Number.isFinite(age)&&age>=-60000&&age<=(feed?.refreshTargetMinutes===60?90:15)*60000&&!feed?.refreshError&&['live','ready','ok'].includes(feed?.status);
    const title=normal(role.title),seen=new Set();
    const jobs=(feed?.jobs||[]).filter(j=>{const key=j.id||j.url;if(!key||seen.has(key))return false;const created=Date.parse(j.created),recent=Number.isFinite(created)&&now-created>=-60000&&now-created<=30*86400000;const p=prefs(),locationOk=!p.location||normal(j.location).includes(normal(p.location)),modeOk=!p.workMode||p.workMode==='any'||j.workMode===p.workMode||p.workMode==='remote'&&j.remote===true;if(!locationOk||!modeOk||!recent||!matchesTitle(role,j.title))return false;seen.add(key);return true;});
    const salaries=jobs.map(j=>{const lo=Number(j.salaryMin),hi=Number(j.salaryMax);return lo>0&&hi>=lo&&hi<300000&&(j.currency==='GBP'||feed?.country==='gb')&&(j.salaryPeriod==='year'||j.salaryPeriod==='annual')?(lo+hi)/2:null;}).filter(Boolean).sort((a,b)=>a-b);
    return {usable:fresh,count:fresh?jobs.length:null,jobs:fresh?jobs:[],label:!fresh?'Market evidence unavailable':jobs.length?'Observed in this feed sample':'No matching sample — demand unknown',salary:fresh&&salaries.length>=3?Math.round((salaries[Math.floor((salaries.length-1)/2)]+salaries[Math.floor(salaries.length/2)])/2):null,salarySamples:salaries.length,checkedAt:feed?.fetchedAt||null};
  }
  function learning(role){return pathway(role).certifications.map(item=>CERT_BY_ID.get(item.id)).filter(c=>c&&(CT.credentials?CT.credentials.availability(c).eligible:!['RETIRED','IN_DEVELOPMENT','UNCONFIRMED'].includes(CT.sourceRegistry?.[c.id]?.credentialStatus)));}
  function options({family='all',search='',shortlist=false,sort='compatibility'}={}){const p=prefs(),q=normal(search);return ROLES.map(r=>assess(r,p)).filter(x=>(family==='all'||x.role.family===family)&&(!shortlist||x.shortlisted)&&(!q||normal(`${x.role.title} ${x.role.mission} ${FAMILIES[x.role.family].label}`).includes(q))).sort((a,b)=>sort==='title'?a.role.title.localeCompare(b.role.title):sort==='readiness'?(b.readiness??-1)-(a.readiness??-1)||b.compatibility-a.compatibility:b.compatibility-a.compatibility||(b.readiness??-1)-(a.readiness??-1));}
  CT.careerOptions=Object.freeze({FAMILIES,ROLES,CONTEXTS,LEVELS,PATHWAY_STAGE_META,PATHWAY_TEMPLATES,ROLE_ROUTE_PROFILES,byId,prefs,update,requirements,evidenceLevel,assess,market,matchesTitle,learning,pathway,pathways,pathwayAudit,options});
  // Normalise every filter label, keeping all saved IDs and legacy memberships.
  const original=global.getFilterDefs;
  if(original)global.getFilterDefs=function(){const defs=original(),all=[...defs.filters,...Object.values(defs.filterGroups).flatMap(g=>g.chips||[])],prior=new Map(all.map(x=>[x.id,x]));
    const filters=defs.filters.filter(x=>!x.groupToggle&&!byId(x.id)&&!CONTEXTS[x.id]),filterGroups={};
    for(const [id,f]of Object.entries(FAMILIES)){const group=`career-${id}`;filters.push({id:`group-${group}`,label:`${f.label} ▾`,groupToggle:group});filterGroups[group]={label:f.label,chips:ROLES.filter(r=>r.family===id).map(r=>{const routeCerts=pathway(r)?.certIds||r.certs;return {...prior.get(r.id),id:r.id,label:r.title,test:c=>routeCerts.includes(c.id)};})};}
    const contexts=Object.entries(CONTEXTS).filter(([id])=>prior.has(id)).map(([id,label])=>({...prior.get(id),label}));
    if(contexts.length){filters.push({id:'group-career-contexts',label:'Sectors, eligibility & work models ▾',groupToggle:'career-contexts'});filterGroups['career-contexts']={label:'Sectors, eligibility & work models',chips:contexts};}
    return {filters,filterGroups};};
})(window);
