// Cert Tracker — adaptive assessment, project review and user-owned market evidence.
(function initCareerMentor(global){
  'use strict';
  const CT=global.CertTrackerV3;
  if(!CT?.careerAdvisor||!CT?.learningResources||!CT?.careerOptions||!CT?.assessmentBank)throw new Error('Career advisor, learning resources, career options and assessment bank must load before career-mentor.js');

  const DEFAULTS=Object.freeze({assessments:{},questionAttempts:{},projects:{},vacancies:[],circumstances:{urgency:'steady',budgetPressure:'normal',workOpportunity:'',constraintNote:''},resourceFeedback:{}});
  const MODES=Object.freeze([
    {key:'explain',label:'Explain',instruction:'Explain the mechanism from first principles, including where it sits in the wider system and one important limitation.'},
    {key:'predict',label:'Predict',instruction:'Predict what should happen in a normal implementation before checking documentation or a lab. State the observations that would confirm it.'},
    {key:'configure',label:'Apply',instruction:'Describe the smallest safe lab that proves you can configure or use this topic. Include validation and rollback.'},
    {key:'troubleshoot',label:'Troubleshoot',instruction:'Assume the service has failed after a change. Give an evidence-led diagnostic order, likely failure boundaries and the proof required before changing anything.'},
    {key:'transfer',label:'Transfer',instruction:'Apply this topic to the selected target role. Explain a realistic decision, trade-off and operational consequence.'}
  ]);
  const clamp=(n,min=0,max=100)=>Math.min(max,Math.max(min,Number(n)||0));
  const today=()=>CT.util.localDateStamp();
  const addDays=(days,from=new Date())=>CT.util.addCalendarDays(from,days);
  function prefs(){const raw=state.customization?.careerMentor;return raw&&typeof raw==='object'?{...DEFAULTS,...raw,circumstances:{...DEFAULTS.circumstances,...(raw.circumstances||{})}}:{...DEFAULTS,circumstances:{...DEFAULTS.circumstances}};}
  function update(patch,label='career mentor'){const current=prefs(),next={...current,...patch};const validation=CT.storage?.validateBackup({version:CT.version.backup,customization:{careerMentor:next}});if(validation&&!validation.ok)throw new Error(validation.errors.join(' '));CT.storage?.captureUndoPoint(label);state.customization={...state.customization,careerMentor:next};save.customization();CT.events?.emit('career-mentor-changed',{});return next;}
  function subjectKey(certId,topic){return `${certId}:${String(topic||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)}`;}
  function attempts(key){return Object.freeze([...(prefs().assessments?.[key]?.attempts||[])]);}
  function appliedMastery(key){const rows=attempts(key).slice(0,6);if(!rows.length)return 0;let weight=0,total=0;rows.forEach((row,index)=>{const w=Math.max(1,6-index),confidence=clamp(row.confidence,1,5),score=clamp(row.score);total+=(score-(confidence>3&&score<60?8:0))*w;weight+=w;});return Math.round(clamp(total/weight));}
  function questionRows(key){return Object.values(prefs().questionAttempts||{}).filter(row=>row?.subjectKey===key&&Array.isArray(row.attempts));}
  function objectiveMastery(key){const rows=questionRows(key).map(row=>row.attempts[0]).filter(Boolean);if(!rows.length)return 0;return Math.round(clamp(rows.filter(row=>row.correct).length/rows.length*100));}
  function mastery(key){const applied=appliedMastery(key),objective=objectiveMastery(key),hasApplied=attempts(key).length>0,hasObjective=questionRows(key).length>0;return Math.round((hasApplied?applied*.55:0)+(hasObjective?objective*.45:0));}
  function due(key){const applied=prefs().assessments?.[key],questions=questionRows(key);return !applied?.nextDue||applied.nextDue<=today()||!questions.length||questions.some(row=>!row.nextDue||row.nextDue<=today());}
  function currentAssessment(advice=CT.careerAdvisor.advise()){
    const cert=advice.primary.cert;if(!cert)return null;const profile=CT.learningResources.profile(cert),rows=profile.subjects.map(subject=>{const key=subjectKey(cert.id,subject.topic);return{subject,key,mastery:mastery(key),due:due(key),attempts:attempts(key).length};}).sort((a,b)=>Number(b.due)-Number(a.due)||a.mastery-b.mastery||a.attempts-b.attempts),pick=rows[0];if(!pick)return null;
    const mode=MODES[pick.attempts%MODES.length],role=advice.role;
    return Object.freeze({...pick,cert,role,mode,prompt:`${mode.instruction} Topic: ${pick.subject.topic}. Target depth: ${pick.subject.depthInfo?.description||`depth ${pick.subject.depth}`}`,criteria:Object.freeze([`Uses accurate ${pick.subject.topic} terminology without hiding behind vendor slogans`,`Shows the mechanism or decision sequence, not just a definition`,`Includes a verification method or observable evidence`,`Identifies one failure mode, limitation or trade-off`,mode.key==='transfer'?`Connects the answer to ${role.title} responsibilities`:'Explains how the topic connects to an adjacent system'])});
  }
  function recordAssessment(key,{score,confidence,notes='',criteriaMet=0}){const p=prefs(),prior=p.assessments?.[key]||{attempts:[]},cleanNotes=String(notes||'').trim().slice(0,2000);if(cleanNotes.length<10)throw new Error('Record at least one concrete observation or correction.');const rubricScore=clamp(criteriaMet,0,5)/5*100,cleanScore=Math.round(Math.min(clamp(score),rubricScore)),interval=cleanScore>=85?30:cleanScore>=70?14:cleanScore>=50?7:cleanScore>=30?3:1,attempt=Object.freeze({id:`attempt-${Date.now()}`,at:new Date().toISOString(),score:cleanScore,confidence:clamp(confidence,1,5),criteriaMet:clamp(criteriaMet,0,5),notes:cleanNotes}),record={attempts:[attempt,...(prior.attempts||[])].slice(0,20),nextDue:addDays(interval),updatedAt:attempt.at};return update({assessments:{...(p.assessments||{}),[key]:record}},'assessment result');}
  function currentKnowledgeCheck(advice=CT.careerAdvisor.advise()){const assessment=currentAssessment(advice);if(!assessment)return null;const records=questionRows(assessment.key),history=Object.fromEntries(records.map(row=>[row.questionId,row])),question=CT.assessmentBank.pick(assessment.cert,assessment.subject,history),previous=records.find(row=>row.questionId===question?.id)?.attempts?.[0]||null;return question?Object.freeze({...assessment,question,previous}):null;}
  function resolveSubject(key){const [certId]=String(key||'').split(':'),cert=CERTS.find(row=>row.id===certId);if(!cert)return null;const subject=CT.learningResources.profile(cert).subjects.find(row=>subjectKey(cert.id,row.topic)===key);return subject?{cert,subject}:null;}
  function recordKnowledge(questionId,{selected,confidence,subjectKey:key}){const question=CT.assessmentBank.get(questionId),context=resolveSubject(key);if(!question)throw new Error('This knowledge check is no longer available.');if(!context||!CT.assessmentBank.candidates(context.cert,context.subject).some(row=>row.question.id===question.id))throw new Error('This knowledge check does not belong to the recorded subject.');const choice=Number(selected);if(!Number.isInteger(choice)||choice<0||choice>=question.options.length)throw new Error('Choose one answer before submitting.');const p=prefs(),recordId=`${question.id}|${key}`,prior=p.questionAttempts?.[recordId]||{attempts:[]},correct=choice===question.answer,certainty=clamp(confidence,1,5),interval=correct?(certainty>=4?21:certainty>=2?10:4):(certainty>=4?1:2),attempt=Object.freeze({id:`knowledge-${Date.now()}`,at:new Date().toISOString(),selected:choice,correct,score:correct?100:0,confidence:certainty}),record={questionId:question.id,subjectKey:key,attempts:[attempt,...(prior.attempts||[])].slice(0,10),nextDue:addDays(interval),updatedAt:attempt.at};update({questionAttempts:{...(p.questionAttempts||{}),[recordId]:record}},'knowledge check');return Object.freeze({correct,selected:choice,answer:question.answer,rationale:question.rationale,question,nextDue:record.nextDue});}
  function certificationMastery(cert){const profile=CT.learningResources.profile(cert),keys=profile.subjects.map(s=>subjectKey(cert.id,s.topic)),scores=keys.map(mastery),appliedCount=keys.reduce((n,key)=>n+attempts(key).length,0),objectiveRows=keys.flatMap(questionRows),objectiveCount=objectiveRows.length,misconceptions=objectiveRows.filter(row=>row.attempts?.[0]?.correct===false&&row.attempts[0].confidence>=4).length,evidenceSubjects=keys.filter(key=>attempts(key).length||questionRows(key).length).length,confidence=objectiveCount>=3&&appliedCount>=2&&evidenceSubjects>=3?'SUPPORTED':objectiveCount>=2&&appliedCount>=1?'DEVELOPING':objectiveCount||appliedCount?'EARLY':'UNASSESSED';return Object.freeze({score:scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):0,assessed:evidenceSubjects,total:scores.length,due:profile.subjects.filter(s=>due(subjectKey(cert.id,s.topic))).length,objectiveCount,appliedCount,evidenceSubjects,misconceptions,confidence,reliable:confidence==='SUPPORTED'});}
  function projectRecord(roleId){return prefs().projects?.[roleId]||{criteria:{},evidence:'',artifactUrl:'',reviewedAt:null};}
  function projectAssessment(advice=CT.careerAdvisor.advise()){const record=projectRecord(advice.role.id),criteria=advice.project.criteria.map((label,index)=>({index,label,met:record.criteria?.[index]===true})),score=criteria.length?Math.round(criteria.filter(x=>x.met).length/criteria.length*100):0;return Object.freeze({record,criteria,score,ready:score===100&&String(record.evidence||'').trim().length>=20});}
  function saveProject(roleId,{criteria,evidence='',artifactUrl=''}){const p=prefs(),safeUrl=/^https:\/\//i.test(String(artifactUrl||''))?String(artifactUrl).slice(0,500):'';return update({projects:{...(p.projects||{}),[roleId]:{criteria:{...(criteria||{})},evidence:String(evidence||'').slice(0,4000),artifactUrl:safeUrl,reviewedAt:new Date().toISOString()}}},'project review');}
  const vacancyKey=row=>{try{const url=new URL(String(row.url||''));url.hash='';for(const key of ['utm_source','utm_medium','utm_campaign','utm_term','utm_content'])url.searchParams.delete(key);return `url:${url.toString().replace(/\/$/,'').toLowerCase()}`;}catch{return `role:${String(row.roleId||'')}|${String(row.title||'').trim().toLowerCase()}|${String(row.employer||'').trim().toLowerCase()}`;}};
  function cleanVacancy(input,id=`vacancy-${Date.now()}-${Math.random().toString(36).slice(2,7)}`){const role=CT.careerOptions.byId(input.roleId);if(!role)throw new Error('Choose a valid target role.');const salaryMin=clamp(input.salaryMin,0,250000),salaryMax=clamp(input.salaryMax,0,250000);if(salaryMin&&salaryMax&&salaryMax<salaryMin)throw new Error('Maximum salary cannot be below minimum salary.');const url=String(input.url||'').trim();if(url&&!/^https:\/\//i.test(url))throw new Error('Vacancy source must use HTTPS.');const row={id,roleId:role.id,title:String(input.title||'').trim().slice(0,160),employer:String(input.employer||'').trim().slice(0,160),url:url.slice(0,500),location:String(input.location||'').trim().slice(0,160),salaryMin,salaryMax,observedAt:String(input.observedAt||today()),outcome:['saved','applied','interview','offer','rejected','withdrawn'].includes(input.outcome)?input.outcome:'saved',notes:String(input.notes||'').slice(0,2000)};if(!row.title||!row.url)throw new Error('Vacancy title and source URL are required.');if(!CT.util.validIsoDate(row.observedAt))throw new Error('Vacancy date must use a real YYYY-MM-DD date.');if(row.observedAt>today())throw new Error('Vacancy observation date cannot be in the future.');return Object.freeze(row);}
  function addVacancy(input){const p=prefs(),row=cleanVacancy(input),duplicate=(p.vacancies||[]).find(existing=>vacancyKey(existing)===vacancyKey(row));if(duplicate)throw new Error(`This vacancy is already recorded as “${duplicate.title}”.`);return update({vacancies:[row,...(p.vacancies||[])].slice(0,200)},'market observation');}
  function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<String(text).length;i++){const c=text[i],next=text[i+1];if(c==='"'&&quoted&&next==='"'){cell+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&next==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell='';}else cell+=c;}row.push(cell);if(row.some(x=>x.trim()))rows.push(row);return rows;}
  function importVacancies(text,defaultRoleId){const table=parseCsv(String(text||'').trim());if(table.length<2)throw new Error('Paste a header row and at least one vacancy.');const headers=table.shift().map(x=>x.trim().toLowerCase()),allowed=['roleid','title','employer','url','location','salarymin','salarymax','observedat','outcome','notes'];if(!headers.includes('title')||!headers.includes('url')||headers.some(x=>!allowed.includes(x)))throw new Error('CSV needs title and url columns and only supported headers.');const p=prefs(),seen=new Set((p.vacancies||[]).map(vacancyKey)),added=[],skipped=[];table.slice(0,200).forEach((cells,index)=>{try{const input=Object.fromEntries(headers.map((header,i)=>[header,cells[i]?.trim()||''])),row=cleanVacancy({roleId:input.roleid||defaultRoleId,title:input.title,employer:input.employer,url:input.url,location:input.location,salaryMin:input.salarymin,salaryMax:input.salarymax,observedAt:input.observedat||today(),outcome:input.outcome,notes:input.notes});const key=vacancyKey(row);if(seen.has(key)){skipped.push(index+2);return;}seen.add(key);added.push(row);}catch(error){throw new Error(`CSV row ${index+2}: ${error.message}`);}});if(!added.length)return Object.freeze({added:0,skipped:skipped.length});update({vacancies:[...added,...(p.vacancies||[])].slice(0,200)},'vacancy CSV import');return Object.freeze({added:added.length,skipped:skipped.length});}
  function updateVacancy(id,patch){const p=prefs(),prior=(p.vacancies||[]).find(row=>row.id===id);if(!prior)throw new Error('Vacancy record no longer exists.');const next=cleanVacancy({...prior,...patch},prior.id),duplicate=(p.vacancies||[]).find(row=>row.id!==id&&vacancyKey(row)===vacancyKey(next));if(duplicate)throw new Error(`This vacancy is already recorded as “${duplicate.title}”.`);return update({vacancies:(p.vacancies||[]).map(row=>row.id===id?next:row)},'application outcome');}
  function removeVacancy(id){const p=prefs();if(!(p.vacancies||[]).some(row=>row.id===id))return p;return update({vacancies:(p.vacancies||[]).filter(row=>row.id!==id)},'remove market observation');}
  function marketSummary(roleId){const cutoff=Date.now()-120*86400000,rows=(prefs().vacancies||[]).filter(row=>row.roleId===roleId&&Date.parse(`${row.observedAt}T12:00:00Z`)>=cutoff),salaries=rows.map(row=>row.salaryMin&&row.salaryMax?(row.salaryMin+row.salaryMax)/2:row.salaryMin||row.salaryMax).filter(Boolean).sort((a,b)=>a-b),middle=Math.floor(salaries.length/2),median=salaries.length?(salaries.length%2?salaries[middle]:(salaries[middle-1]+salaries[middle])/2):null,outcomes=Object.fromEntries(['saved','applied','interview','offer','rejected','withdrawn'].map(key=>[key,rows.filter(r=>r.outcome===key).length])),applications=outcomes.applied+outcomes.interview+outcomes.offer+outcomes.rejected,interviews=outcomes.interview+outcomes.offer,decisions=outcomes.offer+outcomes.rejected,analytics=Object.freeze({applications,interviews,decisions,interviewRate:applications?Math.round(interviews/applications*100):null,offerRate:interviews?Math.round(outcomes.offer/interviews*100):null});return Object.freeze({rows:Object.freeze(rows),count:rows.length,salarySamples:salaries.length,median,outcomes,analytics,dependable:rows.length>=5&&salaries.length>=3,label:rows.length>=5?'Your current vacancy sample':rows.length?'Early personal sample':'No personal vacancy evidence'});}
  function combinedFeed(providerFeed){const rows=(prefs().vacancies||[]).filter(row=>Date.parse(`${row.observedAt}T12:00:00Z`)>=Date.now()-120*86400000).map(row=>({id:row.id,title:row.title,company:row.employer,location:row.location,created:`${row.observedAt}T12:00:00Z`,lastSeenAt:new Date().toISOString(),redirect_url:row.url,url:row.url,salaryMin:row.salaryMin,salaryMax:row.salaryMax,currency:'GBP',salaryPeriod:'annual',query:CT.careerOptions.byId(row.roleId)?.title||'',source:'personal'}));if(!rows.length)return providerFeed;const providerUsable=CT.jobMarket?.usable?.(providerFeed),jobs=[...rows,...(providerUsable?providerFeed.jobs||[]:[])];return{...(providerUsable?providerFeed:{}),schemaVersion:4,status:'ready',provider:providerUsable?`${providerFeed.provider} + your observations`:'Your recorded vacancies',country:'gb',fetchedAt:new Date().toISOString(),lastSuccessfulFetchAt:new Date().toISOString(),refreshTargetMinutes:60,jobs};}
  function resourceRecord(url){return prefs().resourceFeedback?.[url]||null;}
  function rateResource(url,status,note=''){if(!/^https:\/\//i.test(String(url||''))||!['useful','weak','outdated'].includes(status))throw new Error('Invalid resource feedback.');const p=prefs();return update({resourceFeedback:{...(p.resourceFeedback||{}),[url]:{status,note:String(note||'').slice(0,500),updatedAt:new Date().toISOString()}}},'resource feedback');}
  function saveCircumstances(patch){const current=prefs().circumstances||{};return update({circumstances:{...current,...patch,urgency:['steady','soon','urgent'].includes(patch.urgency)?patch.urgency:current.urgency,budgetPressure:['low','normal','high'].includes(patch.budgetPressure)?patch.budgetPressure:current.budgetPressure,workOpportunity:String(patch.workOpportunity??current.workOpportunity??'').slice(0,1000),constraintNote:String(patch.constraintNote??current.constraintNote??'').slice(0,1000)}},'career circumstances');}
  function reviewDue(advisorPrefs=CT.careerAdvisor.prefs()){return !advisorPrefs.nextReviewAt||advisorPrefs.nextReviewAt<=today();}
  function reviewCalendar(advisorPrefs=CT.careerAdvisor.prefs()){const start=String(advisorPrefs.nextReviewAt||addDays(advisorPrefs.reviewCadenceDays||14)).replaceAll('-',''),end=String(addDays(1,new Date(`${advisorPrefs.nextReviewAt||addDays(advisorPrefs.reviewCadenceDays||14)}T12:00:00Z`))).replaceAll('-','');return['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//CertTracker//Career Review//EN','CALSCALE:GREGORIAN','BEGIN:VEVENT',`UID:career-review-${start}@certtracker.local`,`DTSTART;VALUE=DATE:${start}`,`DTEND;VALUE=DATE:${end}`,'SUMMARY:Review career plan','DESCRIPTION:Open Cert Tracker. Record changed circumstances, assessment evidence, project progress and current vacancies before accepting the next recommendation.','END:VEVENT','END:VCALENDAR'].join('\r\n');}
  function projectExport(advice=CT.careerAdvisor.advise()){const project=projectAssessment(advice),lines=[`# ${advice.project.title}`,'',`Target role: ${advice.role.title}`,`Review status: ${project.score}% (${project.ready?'evidence gate met':'not yet complete'})`,`Reviewed: ${project.record.reviewedAt||'Not yet reviewed'}`,'','## Scenario','',advice.project.scenario||advice.project.build||'Use the project brief in Cert Tracker.','','## Build and fault work','',advice.project.build||'',advice.project.faults||'','', '## Assessment criteria','',...project.criteria.map(item=>`- [${item.met?'x':' '}] ${item.label}`),'','## Evidence and reviewer notes','',project.record.evidence||'No evidence recorded.','',project.record.artifactUrl?`Artifact: ${project.record.artifactUrl}`:'Artifact: not linked.','','## Evidence handling','','This export may contain personal or employer-sensitive evidence. Review and redact it before sharing.'];return lines.join('\n');}
  function guidance(advice){const c=prefs().circumstances,market=marketSummary(advice.role.id),cert=advice.primary.cert?certificationMastery(advice.primary.cert):null,project=projectAssessment(advice),notes=[],applications=market.analytics.applications,responses=market.analytics.interviews;if(c.urgency==='urgent'&&advice.assessment.readiness!==null&&advice.assessment.readiness<60)notes.push('Urgent move requested, but current evidence is weak: prioritise an adjacent attainable role rather than jumping to the end-state title.');else if(c.urgency==='soon')notes.push('Near-term move requested: split effort between the decisive learning move and evidence matched to current vacancies.');if(c.budgetPressure==='high')notes.push('Budget pressure is high: exhaust official free material and practical labs before paid courses or another exam booking.');if(c.workOpportunity)notes.push('A workplace evidence opportunity is recorded; use it before inventing a weaker portfolio simulation.');if(cert&&!cert.reliable)notes.push(`Learning evidence is ${cert.confidence.toLowerCase()}: reach at least three marked checks and two applied explanations across three subjects before trusting the mastery estimate.`);if(cert?.misconceptions)notes.push(`${cert.misconceptions} high-confidence wrong answer${cert.misconceptions===1?' is':'s are'} due for deliberate correction before advancing.`);if(project.score<100)notes.push(`Portfolio review is ${project.score}% complete; the role-move gate stays closed.`);if(!market.dependable)notes.push(`Record ${Math.max(0,5-market.count)} more current vacancies for a useful personal demand sample.`);if(applications>=5&&responses/applications<.2)notes.push('Applications are producing few interviews: tighten role targeting, CV evidence and vacancy matching before adding another certification.');else if(market.analytics.interviews>=3&&!market.outcomes.offer)notes.push('Interviews are not converting to offers: prioritise scenario explanation, project defence and interview practice over another credential.');return Object.freeze({circumstances:c,market,certification:cert,project,reviewDue:reviewDue(),notes:Object.freeze(notes)});}

  CT.careerMentor=Object.freeze({DEFAULTS,MODES,prefs,update,subjectKey,attempts,appliedMastery,objectiveMastery,mastery,due,currentAssessment,currentKnowledgeCheck,recordAssessment,recordKnowledge,certificationMastery,projectRecord,projectAssessment,saveProject,projectExport,addVacancy,importVacancies,updateVacancy,removeVacancy,marketSummary,combinedFeed,resourceRecord,rateResource,saveCircumstances,reviewDue,reviewCalendar,guidance});
})(window);
