// Cert Tracker — certification blueprint cross-walk and resource-validation ledger.
// VERIFIED means the recorded domains were checked against a public issuer blueprint.
// Resource validation is independent: a provider page is not automatically aligned material.
(function initCurriculumAudit(global){
  'use strict';
  const CT=global.CertTrackerV3;if(!CT)throw new Error('config.js must load before curriculum-audit.js');
  const CHECKED='2026-09-11';
  const d=(subject,objective,weight=null)=>Object.freeze({subject,objective,weight:weight?Object.freeze(weight):null});
  const r=(label,url,role,status,note,free=null)=>Object.freeze({label,url,role,status,note,free,checkedAt:CHECKED});
  const verified=(version,url,domains,resources=[],note='Public issuer blueprint cross-walked to the tracker subjects.')=>Object.freeze({status:'VERIFIED',version,url,checkedAt:CHECKED,note,domains:Object.freeze(domains),resources:Object.freeze(resources)});
  const pending=(status,url,note)=>Object.freeze({status,version:null,url,checkedAt:null,note,domains:Object.freeze([]),resources:Object.freeze([])});

  const records={
    ccna:verified('200-301 v1.1','https://learningnetwork.cisco.com/s/ccna-exam-topics',[
      d('Network fundamentals','Network fundamentals',[20,20]),d('Network access: switching, VLANs and STP','Network access',[20,20]),d('IP connectivity: routing, OSPF and forwarding','IP connectivity',[25,25]),d('IP services','IP services',[10,10]),d('Security fundamentals','Security fundamentals',[15,15]),d('Automation and programmability','Automation and programmability',[10,10])
    ],[
      r('Cisco U. CCNA learning path','https://u.cisco.com/paths/implementing-administering-cisco-solutions-248','course','BLUEPRINT_ALIGNED','Linked by Cisco from the 200-301 exam page as its guided certification learning path.',null),
      r('Boson NetSim for CCNA','https://boson.com/netsim-cisco-network-simulator/','lab','VERSION_MATCH','Boson lists a 200-301 simulator; use it for applied configuration, not as the official blueprint.',false)
    ]),
    'az-900':verified('Skills measured from 20 July 2026','https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/az-900',[
      d('Cloud concepts','Describe cloud concepts',[25,30]),d('Azure architecture and core services','Describe Azure architecture and services',[35,40]),d('Azure management and governance','Describe Azure management and governance',[30,35])
    ],[r('Microsoft Learn training','https://learn.microsoft.com/en-us/training/','course','ISSUER_RECOMMENDED','Official provider catalogue; select modules from the current AZ-900 credential page.',true)]),
    'az-104':verified('Skills measured from 17 April 2026','https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/az-104',[
      d('Azure identities and governance','Manage Azure identities and governance',[20,25]),d('Storage','Implement and manage storage',[15,20]),d('Compute','Deploy and manage Azure compute resources',[20,25]),d('Virtual networking','Implement and manage virtual networking',[15,20]),d('Monitoring and maintenance','Monitor and maintain Azure resources',[10,15])
    ],[r('Microsoft Learn training','https://learn.microsoft.com/en-us/training/','course','ISSUER_RECOMMENDED','Official provider catalogue; select modules from the current AZ-104 credential page.',true)]),
    'az-700':verified('Skills measured from 27 July 2026','https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/az-700',[
      d('Core Azure networking infrastructure','Design and implement core networking infrastructure',[25,30]),d('Connectivity services','Design, implement and manage connectivity services',[20,25]),d('Application delivery services','Design and implement application delivery services',[15,20]),d('Private access to Azure services','Design and implement private access to Azure services',[10,15]),d('Azure network security services','Design and implement Azure network security services',[15,20])
    ],[r('Microsoft Learn training','https://learn.microsoft.com/en-us/training/','course','ISSUER_RECOMMENDED','Official provider catalogue; select modules from the current AZ-700 credential page.',true)]),
    'sc-300':verified('Skills measured from 27 April 2026','https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/sc-300',[
      d('Identity lifecycle and Entra administration','Implement and manage user identities',[20,25]),d('Authentication and access management','Implement authentication and access management',[25,30]),d('Workload identities and applications','Plan and implement workload identities',[20,25]),d('Identity governance','Plan and automate identity governance',[20,25])
    ],[r('Microsoft Learn training','https://learn.microsoft.com/en-us/training/','course','ISSUER_RECOMMENDED','Official provider catalogue; select modules from the current SC-300 credential page.',true)]),
    'sc-500':verified('Current public skills measured','https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/sc-500',[
      d('Cloud identity and governance security','Manage identity, access and governance',[20,25]),d('Network, storage and database security','Secure storage, databases and networking',[25,30]),d('Compute and workload security','Secure compute',[20,25]),d('Security posture and Defender capabilities','Manage and monitor security posture',[20,25])
    ],[r('Microsoft SC-500 study guide','https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/sc-500','blueprint','BLUEPRINT','Authoritative skills-measured document; reference rather than teaching material.',true),r('Microsoft Learn training','https://learn.microsoft.com/en-us/training/','course','ISSUER_RECOMMENDED','Official provider catalogue; select modules from the current SC-500 credential page.',true)],'The previous separate AI subject was folded into Secure compute because the current issuer blueprint places AI security there.'),
    'az-305':verified('Skills measured from 17 April 2026','https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/az-305',[
      d('Identity, governance and monitoring design','Design identity, governance and monitoring solutions',[25,30]),d('Data storage architecture','Design data storage solutions',[20,25]),d('Business continuity and resilience','Design business continuity solutions',[15,20]),d('Infrastructure architecture','Design infrastructure solutions',[30,35])
    ],[r('Microsoft Learn training','https://learn.microsoft.com/en-us/training/','course','ISSUER_RECOMMENDED','Official provider catalogue; select modules from the current AZ-305 credential page.',true)]),
    pcep:verified('PCEP-30-02','https://pythoninstitute.org/pcep',[
      d('Python syntax, literals and operators','Computer programming fundamentals; Python syntax, semantics, literals, variables, operators and I/O'),d('Control flow','Conditions, loops and flow control'),d('Data collections','Lists, tuples, dictionaries and strings'),d('Functions and exceptions','Built-in and user-defined functions, scope, recursion and exception handling')
    ],[r('Python Essentials 1','https://edube.org/study/pe1','course','BLUEPRINT_ALIGNED','Free issuer-sponsored course explicitly aligned to active PCEP-30-02.',true)]),
    pcap:verified('PCAP-31-03','https://pythoninstitute.org/pcap',[
      d('Modules, packages and namespaces','Modules, packages, PIP and namespaces'),d('Strings and advanced data processing','Character encoding, strings and list processing'),d('Object-oriented programming','Classes, objects, inheritance, polymorphism and OOP modelling'),d('Exceptions, generators and file processing','Exceptions as objects, iterators, generators, closures, files and standard-library modules')
    ],[r('Python Essentials 2','https://edube.org/study/pe2','course','BLUEPRINT_ALIGNED','Free issuer-sponsored course explicitly aligned to active PCAP-31-03.',true)]),
    'a-plus':verified('220-1201 and 220-1202 (V15)','https://www.comptia.org/en-us/certifications/a/core-1-and-2-v15/',[
      d('Core 1: Mobile devices','220-1201 Mobile devices',[15,15]),d('Core 1: Networking','220-1201 Networking',[20,20]),d('Core 1: Hardware','220-1201 Hardware',[25,25]),d('Core 1: Virtualisation and cloud computing','220-1201 Virtualisation and cloud computing',[11,11]),d('Core 1: Hardware and network troubleshooting','220-1201 Hardware and network troubleshooting',[29,29]),d('Core 2: Operating systems','220-1202 Operating systems',[31,31]),d('Core 2: Security','220-1202 Security',[28,28]),d('Core 2: Software troubleshooting','220-1202 Software troubleshooting',[23,23]),d('Core 2: Operational procedures','220-1202 Operational procedures',[18,18])
    ],[r('CompTIA CertMaster / official training','https://www.comptia.org/en-us/training/','course','ISSUER_RECOMMENDED','Issuer training catalogue; confirm the product explicitly names 220-1201 and 220-1202.',false)]),
    'network-plus':verified('N10-009','https://www.comptia.org/en-us/certifications/network/',[
      d('Networking concepts','Networking concepts',[23,23]),d('Network implementation','Network implementation',[20,20]),d('Network operations','Network operations',[19,19]),d('Network security','Network security',[14,14]),d('Network troubleshooting','Network troubleshooting',[24,24])
    ],[r('CompTIA CertMaster / official training','https://www.comptia.org/en-us/training/','course','ISSUER_RECOMMENDED','Issuer training catalogue; confirm the product explicitly names N10-009.',false)]),
    'security-plus':verified('SY0-701','https://www.comptia.org/en-us/certifications/security/',[
      d('General security concepts','General security concepts',[12,12]),d('Threats, vulnerabilities and mitigations','Threats, vulnerabilities and mitigations',[22,22]),d('Security architecture','Security architecture',[18,18]),d('Security operations','Security operations',[28,28]),d('Security program management and oversight','Security program management and oversight',[20,20])
    ],[r('CompTIA CertMaster / official training','https://www.comptia.org/en-us/training/','course','ISSUER_RECOMMENDED','Issuer training catalogue; confirm the product explicitly names SY0-701.',false)]),
    'linux-plus':verified('XK0-006','https://www.comptia.org/en-us/certifications/linux/',[
      d('System management','System management',[23,23]),d('Services and user management','Services and user management',[20,20]),d('Security','Security',[18,18]),d('Automation, orchestration and scripting','Automation, orchestration and scripting',[17,17]),d('Troubleshooting','Troubleshooting',[22,22])
    ],[r('CompTIA CertMaster / official training','https://www.comptia.org/en-us/training/','course','ISSUER_RECOMMENDED','Issuer training catalogue; confirm the product explicitly names XK0-006.',false)]),
    'az-802':verified('Skills measured from 2026 launch','https://learn.microsoft.com/en-us/credentials/certifications/exams/az-802/',[
      d('Active Directory Domain Services','Deploy and manage Active Directory Domain Services',[20,25]),d('Hybrid Windows Server management','Manage Windows Server instances and workloads in a hybrid environment',[10,15]),d('Windows Server virtual machines','Manage virtual machines',[10,15]),d('On-premises and hybrid networking','Implement and manage an on-premises and hybrid networking infrastructure',[10,15]),d('Storage and file services','Manage storage and file services',[15,20]),d('Windows Server infrastructure security','Secure Windows Server infrastructure',[10,15]),d('Monitoring and troubleshooting','Monitor and troubleshoot Windows Server environments',[15,20])
    ],[r('Microsoft Learn AZ-802 training','https://learn.microsoft.com/en-us/credentials/certifications/exams/az-802/','course','ISSUER_RECOMMENDED','Use the training paths linked from the live exam page and retain hands-on AD DS, hybrid, VM, networking, storage, security and recovery labs.',true)],'Seven weighted domains replace the former compressed six-subject representation.'),
    'crowdstrike-ccfa':verified('Certification guide updated February 2026','https://www.crowdstrike.com/content/dam/crowdstrike/marketing/en-us/documents/pdfs/crowdstrike-university/ccfa-certification-guide.pdf',[
      d('User management','User management'),d('Sensor deployment','Sensor deployment'),d('Host management and setup','Host management and setup'),d('Group creation','Group creation'),d('Policy application','Policy application'),d('Rules configuration','Rules configuration'),d('Dashboards and reports','Dashboards and reports'),d('Workflows','Workflows')
    ],[r('CrowdStrike University CCFA curriculum','https://www.crowdstrike.com/services/training-and-education/','course','ISSUER_RECOMMENDED','Official training is recommended but access may depend on customer/partner entitlement.',false)]),
    'ccnp-enterprise':verified('350-401 ENCOR plus 300-410 ENARSI','https://www.cisco.com/site/us/en/learn/training-certifications/certifications/enterprise/ccnp-enterprise/index.html',[
      d('Enterprise architecture and virtualisation','ENCOR architecture and virtualisation'),d('Enterprise infrastructure','ENCOR infrastructure'),d('Network assurance','ENCOR network assurance'),d('Infrastructure security','ENCOR and ENARSI infrastructure security'),d('Automation and programmability','ENCOR and ENARSI automation'),d('Advanced routing and VPN services','ENARSI Layer 3 and VPN services'),d('Infrastructure services and troubleshooting','ENARSI infrastructure services and troubleshooting')
    ],[r('Cisco U. CCNP Enterprise training','https://u.cisco.com/','course','ISSUER_RECOMMENDED','Use current ENCOR and ENARSI learning paths and labs.',false)]),
    'ai-901':verified('Skills measured from 15 April 2026','https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/ai-901',[
      d('AI concepts and capabilities','Identify AI concepts and capabilities',[40,45]),d('Microsoft Foundry AI solutions','Implement AI solutions using Microsoft Foundry',[55,60])
    ],[r('Microsoft Learn AI-901 training','https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/ai-901','course','ISSUER_RECOMMENDED','Follow the live study-guide training links and add a small Foundry exercise.',true)]),
    'ai-103':verified('Skills measured from 16 April 2026','https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/ai-103',[
      d('Plan and manage an Azure AI solution','Plan and manage an Azure AI solution',[25,30]),d('Generative AI and agents','Implement generative AI solutions and agents',[30,35]),d('Computer vision','Implement a computer vision solution',[10,15]),d('Text analysis','Implement a text analysis solution',[10,15]),d('Information extraction','Implement an information extraction solution',[10,15])
    ],[r('Microsoft Learn AI-103 training','https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/ai-103','course','ISSUER_RECOMMENDED','Use the live study-guide learning path and Microsoft Foundry labs.',true)]),
    pcpp1:verified('PCPP-32-101','https://pythoninstitute.org/pcpp1',[
      d('Advanced object-oriented programming','Advanced classes and object-oriented programming'),d('Coding conventions and documentation','PEP 8, PEP 257, quality and documentation'),d('GUI programming','GUI programming'),d('Network programming and APIs','Sockets, JSON/XML, HTTP and REST'),d('File, data and environment modules','sqlite3, XML, CSV, logging, configuration, OS, date/time and I/O modules')
    ],[r('Advanced Python 1','https://edube.org/study/pe3','course','BLUEPRINT_ALIGNED','Issuer-sponsored advanced course for the PCPP1 scope; confirm the current exam-code alignment before relying on it alone.',true)]),
    'ccie-enterprise':verified('350-401 ENCOR plus CCIE Enterprise Infrastructure lab v1.1','https://www.cisco.com/site/us/en/learn/training-certifications/certifications/enterprise/ccie-enterprise-infrastructure/index.html',[
      d('Network infrastructure design','Plan and design dual-stack enterprise infrastructure'),d('Software-defined infrastructure','Software-defined infrastructure'),d('Transport technologies','Transport technologies and services'),d('Infrastructure security and services','Infrastructure security and services'),d('Automation and programmability','Automation, scripting, APIs and HTTP'),d('Operate and optimise','Deploy, operate, troubleshoot and optimise under practical lab conditions')
    ],[r('Cisco U. CCIE Enterprise learning matrix','https://u.cisco.com/','course','ISSUER_RECOMMENDED','Use the current learning matrix with extensive legal lab practice; an expert badge cannot be earned from reading alone.',false)]),
    cwna:verified('CWNA-109; CWNA-110 transition disclosed','https://www.cwnp.com/certifications/cwna',[
      d('RF technologies','Radio-frequency technologies'),d('Antennas and WLAN hardware','Antennas, WLAN hardware and software'),d('802.11 architecture and protocols','802.11 standards and architecture'),d('WLAN security','WLAN security'),d('Site surveys and implementation','Site survey, installation and implementation'),d('WLAN management and troubleshooting','WLAN management and troubleshooting')
    ],[r('CWNP CWNA study products','https://www.cwnp.com/certifications/cwna','course','VERSION_MATCH','Issuer page identifies current CWNA-109 materials and the CWNA-110 transition; select material matching the booked exam.',false)]),
    'cisco-meraki-solutions':verified('500-220 ECMS','https://learningnetwork.cisco.com/s/ecms-exam-topics',[
      d('Cloud and network management','Cloud and network management',[15,15]),d('Meraki solution design','Design',[20,20]),d('Meraki implementation','Implementation',[25,25]),d('Monitoring and troubleshooting','Monitoring and troubleshooting',[20,20]),d('Security and policies','Security and policies',[20,20])
    ],[r('Cisco Engineering Cisco Meraki Solutions training','https://www.cisco.com/site/us/en/learn/training-certifications/training/courses/ecms.html','course','BLUEPRINT_ALIGNED','Official Cisco ECMS training; combine with authorised Meraki Dashboard practice.',false)]),
    cwap:verified('CWAP-405','https://www.cwnp.com/certifications/cwap',[
      d('PHY behaviour','802.11 PHY behaviour'),d('MAC operations','802.11 MAC operations'),d('802.11 frame exchanges','802.11 frame exchanges'),d('Spectrum analysis','Spectrum analysis and troubleshooting'),d('Protocol analysis and troubleshooting','Protocol analysis and troubleshooting')
    ],[r('CWNP CWAP study products','https://www.cwnp.com/certifications/cwap','course','VERSION_MATCH','Issuer material for active CWAP-405; add legal packet and spectrum capture practice.',false)]),
    cwdp:verified('CWDP-305','https://www.cwnp.com/certifications/cwdp',[
      d('WLAN design methodology','WLAN design methodology'),d('Architecture and protocols','Architecture and protocols'),d('Site survey planning','Site survey planning'),d('Security design','Security design'),d('Design validation and optimisation','Validation and optimisation')
    ],[r('CWNP CWDP study products','https://www.cwnp.com/certifications/cwdp','course','VERSION_MATCH','Issuer material for active CWDP-305; require a complete multi-vendor design pack.',false)]),
    cwsp:verified('CWSP-208','https://www.cwnp.com/certifications/cwsp',[
      d('WLAN discovery and attacks','Discovery, attacks and protocol analysis'),d('Security protocol analysis','Security protocol analysis'),d('Secure WLAN design','Secure design models and endpoints'),d('Authentication and key management','Authentication and key management'),d('802.1X, EAP and roaming','802.1X, EAP and fast roaming'),d('WIPS, monitoring and policy','WIPS, monitoring systems and policy')
    ],[r('CWNP CWSP study products','https://www.cwnp.com/certifications/cwsp','course','VERSION_MATCH','Issuer material for active CWSP-208; reinforce with authorised authentication and attack/defence labs.',false)]),
    cwisa:verified('CWISA-103','https://www.cwnp.com/certifications/cwisa',[
      d('Wireless IoT foundations','Wireless-IoT foundations'),d('Short-range wireless protocols','802.15.4, Zigbee, Thread and Bluetooth'),d('LPWAN technologies','LoRaWAN, Sigfox and other LPWAN technologies'),d('Location services','Wireless location services'),d('Supporting networks and APIs','Wired support, APIs and automation awareness'),d('IoT operations and project fundamentals','Operations and project fundamentals')
    ],[r('CWNP CWISA study products','https://www.cwnp.com/certifications/cwisa','course','VERSION_MATCH','Issuer material for active CWISA-103. This is retained only as the current CWNE prerequisite gate.',false)]),
    cwne:verified('Current application requirements','https://www.cwnp.com/certifications/cwne',[
      d('Current CWNA/CWAP/CWDP/CWSP','Current professional certification set'),d('Commercial WLAN deployment evidence','Documented commercial WLAN deployments'),d('External networking credential','Accepted external networking credential and CWISA requirement'),d('Recommendations and peer review','Recommendations and peer review'),d('Continuing education','Ongoing continuing education')
    ],[], 'Experience-gated application requirements are represented as evidence domains, not exam topics.')
  };

  const queue={
    mcit:['ACCESS_RESTRICTED','https://www.milestonesys.com/learn-and-support/learning-and-performance/','Exact course objectives require Milestone Learning & Performance access.'],
    mcde:['ACCESS_RESTRICTED','https://www.milestonesys.com/learn-and-support/learning-and-performance/','Exact design-course objectives require Milestone Learning & Performance access.'],
    mcie:['ACCESS_RESTRICTED','https://www.milestonesys.com/learn-and-support/learning-and-performance/','Exact integration-engineer objectives require Milestone Learning & Performance access.'],
    acp:['ACCESS_RESTRICTED','https://www.axis.com/learning/certification-program','Validate the current exam specification and training modules through Axis learning access.'],
    'arcules-csp':['ACCESS_RESTRICTED','https://arcules.com/','Certification curriculum requires the partner learning portal.'],
  };
  for(const[id,[status,url,note]]of Object.entries(queue))records[id]=pending(status,url,note);
  const ROUTE_IMPACT=Object.freeze({'network-plus':49,'security-plus':42,'a-plus':36,'az-104':20,pcep:11,'az-900':11,pcap:11,'az-305':9,'linux-plus':8,'sc-300':8,mcie:6,acp:6,ccna:6,cwna:6,'cisco-meraki-solutions':6,'crowdstrike-ccfa':6,pcpp1:6,mcde:4,mcit:3,'sc-500':3,'ccnp-enterprise':3,'az-802':2,'az-700':2,'ccie-enterprise':2,'arcules-csp':1,'ai-901':0,'ai-103':0});
  const frozen=Object.freeze(Object.fromEntries(Object.entries(records).map(([id,value])=>[id,Object.freeze({...value,certId:id,routeImpact:ROUTE_IMPACT[id]||0})])));
  function record(id){return frozen[id]||null;}
  function validatedResources(id){return Object.freeze((record(id)?.resources||[]).filter(x=>['BLUEPRINT_ALIGNED','VERSION_MATCH'].includes(x.status)));}
  function queueRows(){return Object.freeze(Object.values(frozen).filter(x=>x.status!=='VERIFIED').sort((a,b)=>b.routeImpact-a.routeImpact||a.certId.localeCompare(b.certId)));}
  function summary(){const rows=Object.values(frozen),coreIds=new Set(global.CERT_TRACKER_FOCUSED_ROUTE?.ids||[]),core=rows.filter(x=>coreIds.has(x.certId)),focus=rows.filter(x=>!coreIds.has(x.certId));return Object.freeze({scope:rows.length,verified:rows.filter(x=>x.status==='VERIFIED').length,queued:rows.filter(x=>x.status==='QUEUED'||x.status==='SOURCE_IDENTIFIED').length,restricted:rows.filter(x=>x.status==='ACCESS_RESTRICTED').length,validatedResources:rows.reduce((n,x)=>n+validatedResources(x.certId).length,0),coreScope:core.length,coreVerified:core.filter(x=>x.status==='VERIFIED').length,coreRestricted:core.filter(x=>x.status==='ACCESS_RESTRICTED').length,focusScope:focus.length,focusVerified:focus.filter(x=>x.status==='VERIFIED').length});}
  CT.curriculumAudit=Object.freeze({STATUSES:Object.freeze(['VERIFIED','SOURCE_IDENTIFIED','ACCESS_RESTRICTED','QUEUED']),RESOURCE_STATUSES:Object.freeze(['BLUEPRINT','BLUEPRINT_ALIGNED','VERSION_MATCH','ISSUER_RECOMMENDED']),records:frozen,record,validatedResources,queue:queueRows,summary});
})(window);
