// Cert Tracker — generic learning-first topic recommendation engine.
// Topics are curriculum units, not credentials. Personal mastery remains browser-local.
(function initTopicEngine(global){
  'use strict';
  const CT=global.CertTrackerV3;
  if(!CT?.competency||!CT?.careerFramework||!CT?.capabilityGates||!CT?.recommendations)throw new Error('Competency, career, capability and recommendation engines must load before topic-engine.js');

  const TOPICS=Object.freeze([
    {id:'vms-network-troubleshooting',phase:1,title:'VMS + IP video network troubleshooting',skills:['vms','physical','networking'],certs:['mcie','acp','briefcam-tech'],evidence:'physical-vms-breakfix',why:'Connect application symptoms to device, service, transport and network causes instead of treating VMS and networking as separate problems.',actions:['Trace one camera stream end-to-end','Map ports, services and dependencies','Write a root-cause note from a real or lab fault']},
    {id:'ethernet-vlans-packet-flow',phase:1,title:'Ethernet, VLANs, switching and packet flow',skills:['networking','routing'],certs:['ccna'],evidence:'network-routed-topology',why:'This is the foundation underneath routing, segmentation, firewalls and multi-site security systems.',actions:['Build two VLANs and inter-VLAN routing','Predict the L2/L3 forwarding path before testing','Break trunk/access settings and diagnose the symptoms']},
    {id:'packet-analysis-core',phase:1,title:'Packet analysis: ARP, DHCP, DNS, TCP and TLS',skills:['networking','pki'],certs:['ccna','security-plus'],evidence:'network-packet-analysis',why:'Packet capture turns troubleshooting from assumption into evidence and transfers directly into later security work.',actions:['Capture ARP + DHCP + DNS exchanges','Follow a TCP session and retransmissions','Identify where TLS begins and what remains visible']},
    {id:'enterprise-wifi-rf',phase:2,title:'Multi-vendor enterprise Wi-Fi: RF, survey, roaming and troubleshooting',skills:['networking','wireless'],certs:['cwna','cwap','cwdp','cwsp'],evidence:'network-wireless-validation',why:'Vendor-neutral RF and 802.11 reasoning transfers across Meraki, Ubiquiti and enterprise WLAN platforms instead of teaching one controller interface.',actions:['Create a predictive and measured survey plan','Capture and explain association, authentication and roaming','Diagnose co-channel interference, coverage and capacity faults with packet and spectrum evidence']},
    {id:'cellular-wan-operations',phase:2,title:'4G/5G cellular WAN, antennas, carrier behaviour and failover',skills:['networking','wireless','resilience'],certs:['cwna','network-plus'],evidence:'network-cellular-wan',why:'CWNP strengthens RF reasoning but does not replace operational cellular-router knowledge, carrier/APN design or resilient WAN testing.',actions:['Compare LTE/5G bands, signal metrics and antenna choices','Configure APN, routing, NAT and dual-WAN failover in a legal lab','Record throughput, latency, jitter and recovery behaviour under degraded signal']},
    {id:'cellular-radio-diagnostics',phase:3,title:'Cellular radio diagnostics and field validation',skills:['networking','wireless'],certs:['cwna'],evidence:'network-cellular-wan',why:'Reliable cellular deployments require interpreting RSRP, RSRQ, SINR, RSSI, band selection, aggregation and antenna placement instead of relying on signal bars.',actions:['Capture baseline RSRP/RSRQ/SINR by location and band','Compare omni/directional and MIMO antenna placement','Correlate radio metrics with throughput, latency and packet loss']},
    {id:'cellular-carrier-core',phase:4,title:'Carrier, SIM/eSIM, APN and private 5G architecture',skills:['networking','architecture','wireless'],certs:[],evidence:'network-cellular-design',why:'Architect-level cellular work needs the service model behind the router: addressing, CGNAT, public/private APNs, roaming, QoS, slicing concepts and private cellular boundaries.',actions:['Diagram UE/router, RAN, transport and packet-core flow','Compare public, fixed-IP and private APN options','Model SIM lifecycle, roaming, carrier escalation and private-5G integration']},
    {id:'cellular-security-resilience',phase:5,title:'Cellular WAN security, resilience and fleet observability',skills:['networking','security','resilience','architecture'],certs:[],evidence:'network-cellular-design',why:'A production fleet must survive carrier, radio, hardware and management-plane failures without creating an unmanaged security bypass.',actions:['Threat-model device, SIM, carrier and cloud-management planes','Design encrypted overlay, segmentation and least-privilege remote management','Define dual-carrier failover tests, telemetry, alerting and recovery runbooks']},
    {id:'cellular-architecture-capstone',phase:6,title:'Multi-site enterprise cellular architecture capstone',skills:['networking','wireless','architecture','security','resilience'],certs:['ccie-enterprise'],evidence:'network-cellular-design',why:'This is the cellular peer to the expert networking capstone: a defensible design and fault exercise, not a fictional credential.',actions:['Produce HLD/LLD, coverage assumptions, carrier options and BoM for a multi-site estate','Validate primary/backup and out-of-band scenarios under timed faults','Defend security, cost, operational ownership and migration trade-offs with measured evidence']},
    {id:'access-control-architecture',phase:1,title:'Access-control architecture: controllers, readers, OSDP and identity',skills:['access','accessIdentity','physical','apiIntegration'],certs:['lca','acp'],evidence:'physical-access-architecture',why:'Physical-security convergence requires PACS architecture knowledge as well as strong video/VMS knowledge.',actions:['Draw reader → controller → server data flow','Compare OSDP with legacy Wiegand','Model credential lifecycle and VMS event integration']},
    {id:'windows-ad-dns-foundations',phase:1,title:'Windows Server, AD DS and DNS foundations',skills:['windows','enterpriseInfra'],certs:['az-802','mcie'],evidence:'infra-ad-dns-pki',why:'Enterprise security platforms depend on identity, name resolution, server roles and certificates even when those systems are hidden beneath the application.',actions:['Build a small AD DS domain','Create and troubleshoot forward/reverse DNS','Join a server/workstation and validate authentication flow']},
    {id:'routing-ospf-bgp',phase:2,title:'Advanced routing: OSPF, BGP, route control and failure analysis',skills:['routing','networking'],certs:['ccnp-enterprise','ccie-enterprise'],evidence:'network-breakfix',why:'Deep routing knowledge is highly transferable across firewalls, cloud, OT segmentation and multi-site architectures.',actions:['Build multi-area or multi-site routing','Introduce route-selection faults deliberately','Prove the chosen path from control plane and packet evidence']},
    {id:'firewall-nat-vpn',phase:2,title:'Firewall policy, NAT, VPNs and session flow',skills:['firewall','networking'],certs:['security-plus','pan-netsec-pro','pan-ngfw-eng'],evidence:'security-firewall-policy',why:'Network security becomes practical when you can predict and troubleshoot the complete session path rather than only write policy rules.',actions:['Model source/destination NAT','Build site-to-site VPN behaviour','Troubleshoot a denied or asymmetric session from logs and packets']},
    {id:'segmentation-data-flows',phase:2,title:'Segmentation, trust boundaries and permitted data flows',skills:['firewall','architecture','networking','ot'],certs:['pan-ngfw-eng','iec-62443-cfs'],evidence:'security-segmentation',why:'Segmentation is a convergence skill spanning enterprise, cloud, physical security and OT environments.',actions:['Create a zone/VLAN design','Write an explicit flow matrix','Validate least-privilege rules against real application dependencies']},
    {id:'pki-tls-lifecycle',phase:2,title:'PKI, TLS and certificate lifecycle troubleshooting',skills:['pki','enterpriseInfra','iam'],certs:['az-802','security-plus'],evidence:'infra-ad-dns-pki',why:'Certificates repeatedly surface in VMS, web services, VPNs, APIs, cloud and OT integrations.',actions:['Build or inspect a certificate chain','Test expiry/name/trust failures','Document issuance, renewal and revocation paths']},
    {id:'storage-ha-recovery',phase:2,title:'Storage, capacity, HA, backup and recovery',skills:['storage','resilience','enterpriseInfra','database'],certs:['az-802'],evidence:'infra-ha-dr',why:'System design fails when compute/storage/recovery assumptions are weak, especially for high-throughput video platforms.',actions:['Calculate storage/retention for a sample workload','Define RPO/RTO and recovery order','Test a backup/restore or simulated failover']},
    {id:'hybrid-azure-networking',phase:3,title:'Hybrid Azure networking and private connectivity',skills:['azure','cloud','hybridNetwork','networking'],certs:['az-104','az-700','az-305','sc-500'],evidence:'cloud-hybrid-network',why:'Cloud should extend networking knowledge rather than become a disconnected administration track.',actions:['Build VNets/subnets/routes/NSGs','Trace DNS and private endpoint behaviour','Design VPN/ExpressRoute-style hybrid connectivity']},
    {id:'cloudflare-edge-foundations',phase:3,title:'Cloudflare DNS, CDN, TLS, WAF and DDoS foundations',skills:['cloud','networking','pki','security'],certs:[],evidence:'cloud-edge-security',why:'Edge services join DNS, routing, TLS, performance and security; understanding the full request path prevents unsafe point-and-click deployments.',actions:['Publish a legal test zone and trace authoritative DNS and proxy behaviour','Configure TLS modes, caching and a narrowly scoped WAF rule','Measure origin exposure, headers, latency and failure behaviour']},
    {id:'cloudflare-zero-trust',phase:4,title:'Cloudflare Zero Trust, tunnels and secure access',skills:['cloud','iam','zeroTrust','networking'],certs:[],evidence:'cloud-edge-security',why:'Identity-aware access and outbound tunnels can remove public exposure, but require deliberate identity, policy, DNS and operational design.',actions:['Connect a lab service through Cloudflare Tunnel','Apply identity-aware least-privilege access and test denial paths','Document connector availability, logging, break-glass and outage behaviour']},
    {id:'cloudflare-architecture-capstone',phase:5,title:'Cloudflare edge-security architecture capstone',skills:['architecture','cloud','security','resilience','commercial'],certs:[],evidence:'cloud-edge-security',why:'Cloudflare becomes architecturally valuable when product settings are translated into trust boundaries, availability choices, telemetry and commercial trade-offs.',actions:['Produce an HLD/LLD for DNS, edge security, private access and origin protection','Threat-model bypass, identity, certificate, tunnel and vendor-outage scenarios','Compare Cloudflare with native-cloud or alternate SASE controls using cost, lock-in and operations criteria']},
    {id:'identity-oauth-oidc',phase:3,title:'Identity flows: Entra, OAuth, OIDC and privileged access',skills:['iam','zeroTrust','apiIntegration'],certs:['sc-300','sc-100'],evidence:'cloud-identity-flow',why:'Modern convergence architectures increasingly depend on identity-aware access and API authentication rather than only network location.',actions:['Trace authorization-code flow','Separate authentication from authorization','Model privileged and service identities']},
    {id:'security-monitoring-telemetry',phase:3,title:'Security monitoring, telemetry and incident reasoning',skills:['soc','siem','incident','threat'],certs:['cysa-plus','sc-200'],evidence:'security-monitoring',why:'Architecture quality improves when you understand what defenders can actually observe during failure or attack.',actions:['Investigate a small telemetry set','Build a timeline from multiple events','Identify the monitoring gap that prevented certainty']},
    {id:'python-api-automation',phase:3,title:'Python + REST APIs for operational automation',skills:['python','automation','apiIntegration'],certs:['pcep','pcap','pcpp1'],evidence:'automation-api-integration',why:'Programming becomes strategically useful when it removes repetitive work and integrates systems that were not designed together.',actions:['Authenticate to a test API','Parse and validate JSON responses','Turn the script into a reusable inventory or health-check tool']},
    {id:'ot-control-fundamentals',phase:4,title:'PLC, HMI, SCADA, I/O and control-loop fundamentals',skills:['otEngineering','industrialProtocols'],certs:['isa-cap-associate','gicsp'],evidence:'ot-plc-hmi',why:'OT security knowledge has a hard ceiling if the control process itself remains a black box.',actions:['Build or simulate PLC + HMI logic','Explain scan cycle and digital/analogue I/O','Trace a sensor → logic → actuator control loop']},
    {id:'industrial-protocols',phase:4,title:'Industrial protocols: Modbus TCP, OPC UA, MQTT and BACnet/IP',skills:['industrialProtocols','otEngineering','networking'],certs:['isa-cap-associate','gicsp','isa95-fund'],evidence:'ot-protocols',why:'Protocol literacy is essential for segmentation, monitoring, troubleshooting and IT/OT integration decisions.',actions:['Capture two protocol exchanges','Identify addressing/function semantics','Explain normal traffic and what a risky command would look like']},
    {id:'ot-zones-conduits',phase:4,title:'IEC 62443 zones, conduits and OT risk-driven segmentation',skills:['ot','firewall','architecture','governance'],certs:['iec-62443-cfs','iec-62443-cra','iec-62443-cds'],evidence:'ot-risk-assessment',why:'This connects cyber risk to actual industrial architecture instead of treating 62443 as theory-only.',actions:['Inventory assets and trust zones','Define conduits and required flows','Map threats and controls to a sample industrial site']},
    {id:'isa95-integration',phase:4,title:'ISA-95 enterprise-control integration and information flows',skills:['otEngineering','architecture','apiIntegration'],certs:['isa95-fund'],evidence:'ot-process-literacy',why:'Convergence architecture depends on knowing where enterprise, operations and control responsibilities meet.',actions:['Map enterprise/control levels for a sample site','Identify MES/ERP/control data exchanges','Document ownership and integration boundaries']},
    {id:'architecture-hld-lld',phase:4,title:'Architecture practice: requirements, HLD, LLD and decision records',skills:['architecture','commercial','networking','enterpriseInfra'],certs:['bcs-arch-found','bcs-arch-solution','bcs-arch-security','bcs-esa'],evidence:'architecture-hld-lld',why:'Architecture credentials are most useful when every concept is attached to a real design artefact.',actions:['Turn requirements into constraints and principles','Create HLD then implementation-focused LLD','Record options, decisions and rejected alternatives']},
    {id:'commercial-delivery',phase:5,title:'Commercial architecture: BoM, TCO, migration and supportability',skills:['commercial','architecture','leadership','resilience'],certs:['bcs-esa','isa-apm','sabsa-found'],evidence:'architecture-bom-tco',why:'Senior architecture is the ability to choose a design that can actually be bought, delivered, supported and defended.',actions:['Build a BoM/licensing model','Compare CapEx/OpEx and lifecycle cost','Create migration, acceptance and support assumptions']},
    {id:'ai-analytics-architecture',phase:5,title:'AI/video analytics architecture, quality and security',skills:['aiSystems','aiSecurity','data','privacy','apiIntegration'],certs:['briefcam-tech','ai-901','secai-plus','sc-500'],evidence:'ai-inference-architecture',why:'AI becomes a differentiator when you can reason about data quality, inference placement, compute, privacy and security rather than only product features.',actions:['Compare edge vs cloud inference','Model false-positive/false-negative trade-offs','Threat-model model/API/data supply chain']},
    {id:'functional-safety-sis',phase:5,title:'Functional safety, SIS and SIL concepts',skills:['otEngineering','governance','architecture'],certs:['isa-61511-sis-fund','isa-61511-sil-select','isa-61511-sil-verify','isa-61511-expert'],evidence:'ot-process-literacy',roleDriven:true,why:'This matters when convergence work enters process, energy or CNI environments where safety functions and cyber controls interact.',actions:['Separate BPCS from SIS responsibilities','Explain SIL as risk reduction, not cybersecurity level','Map safety lifecycle and cyber-security touchpoints']}
  ].map(x=>Object.freeze({...x,skills:Object.freeze(x.skills),certs:Object.freeze(x.certs),actions:Object.freeze(x.actions)})));

  function phase(){return Math.max(1,Math.min(6,Number(CT.phases?.currentPhase?.()||1)));}
  function roleWeight(topic,roleKey){const role=CT.careerFramework.ROLE_PROFILES[roleKey];if(!role)return 0;return topic.skills.reduce((sum,s)=>sum+Number(role.weights[s]||0),0)/Math.max(1,topic.skills.length);}
  function skillMastery(topic){const p=CT.competency.profile();return topic.skills.reduce((sum,s)=>sum+Number(p[s]||0),0)/Math.max(1,topic.skills.length);}
  function evidenceMastery(topic){return topic.evidence?CT.capabilityGates.evidenceRecord(topic.evidence).score/100:0;}
  function mastery(topic){return Math.round((skillMastery(topic)*.72+evidenceMastery(topic)*.28)*100);}
  function certSynergy(topic,cert){if(!cert)return 0;if(topic.certs.includes(cert.id))return 1;const comp=CT.competency.competencies(cert);const hits=topic.skills.filter(skill=>comp[skill]).length;return hits/Math.max(1,topic.skills.length);}
  function score(topic,options={}){
    const ctx=CT.careerFramework.context();const currentPhase=phase();const cert=options.cert||null;const m=mastery(topic)/100;
    const gap=1-m;const current=roleWeight(topic,ctx.current);const next=roleWeight(topic,ctx.next);const target=roleWeight(topic,ctx.target);
    const phaseDistance=topic.phase-currentPhase;const timing=phaseDistance===0?1:phaseDistance===1?.72:phaseDistance<0?.55:Math.max(.08,1-phaseDistance*.28);
    const evidenceNeed=topic.evidence?(1-evidenceMastery(topic)):0;const synergy=certSynergy(topic,cert);
    const rolePenalty=topic.roleDriven&&target<.25&&next<.25?.45:1;
    const total=(gap*38+current*18+next*16+target*10+timing*8+synergy*7+evidenceNeed*3)*rolePenalty;
    const reasons=[];if(gap>.55)reasons.push(`${Math.round(gap*100)}% learning/evidence gap`);if(current>.45)reasons.push('Strong current-role value');if(next>.45)reasons.push('Strong next-role value');if(synergy>.5&&cert)reasons.push(`Directly reinforces ${cert.name}`);if(topic.evidence&&evidenceNeed>.5)reasons.push('Practical evidence still weak');if(topic.phase===currentPhase)reasons.push(`Phase ${topic.phase} focus`);
    return Object.freeze({topic,score:Math.round(total),mastery:Math.round(m*100),phase:topic.phase,reasons:Object.freeze(reasons),certSynergy:Math.round(synergy*100)});
  }
  function focusedTopics(){
    const route=CT.focusedRoute;
    if(!route?.enabled())return TOPICS;
    const rows=TOPICS.filter(t=>t.certs.some(id=>route.definition.ids.includes(id))).map(t=>({...t,phase:Math.min(...t.certs.filter(id=>route.definition.ids.includes(id)).map(id=>route.phase(id)))}));
    rows.push({id:'focused-system-foundations',phase:1,title:'Systems and IP-network foundations',skills:['windows','networking'],certs:['a-plus','network-plus','mcit','mcde','arcules-csp'],why:'Understand the systems underneath security applications before adding advanced platform credentials.',actions:['Trace device, network and service dependencies','Practise DNS and connectivity diagnostics','Understand storage, backup and recovery basics']});
    rows.push({id:'focused-systems-automation',phase:2,title:'PowerShell, Git and systems fundamentals',skills:['automation','windows'],certs:['pcep','pcap'],why:'Support Python with practical administration, version control and safe changes; no additional exam ladder.',actions:['Version a reusable script in Git','Handle credentials and errors safely','Understand Windows/Linux services, storage, backup and recovery']});
    rows.push({id:'focused-linux-administration',phase:3,title:'Linux administration and troubleshooting',skills:['linux','networking','automation'],certs:['linux-plus'],why:'Build the operating-system depth underneath networking, cloud platforms and Python automation.',actions:['Manage users, permissions, packages, storage and services','Troubleshoot SSH, networking and service logs','Write and safely test reusable Bash administration scripts']});
    rows.push({id:'focused-falcon-administration',phase:3,title:'Falcon endpoint administration',skills:['security','automation'],certs:['crowdstrike-ccfa'],why:'Operate endpoint controls safely alongside the Microsoft platform, without adding responder or hunter exams.',actions:['Practise staged sensor deployment and rollback','Assign host groups, roles and prevention/update policies','Check supported Defender coexistence and audit workflows']});
    rows.push({id:'focused-ai-applications',phase:5,title:'Python AI applications and agents',skills:['python','apiIntegration'],certs:['ai-103'],why:'Turn Python and Azure knowledge into evaluated, maintainable AI integrations.',actions:['Use Microsoft Foundry with managed credentials','Evaluate grounding, failures and cost','Test API handling and deployment automation']});
    return rows;
  }
  function recommend(options={}){const limit=Math.max(1,Number(options.limit||5));const currentPhase=phase();return focusedTopics().map(topic=>score(topic,options)).filter(row=>row.mastery<88&&row.phase<=currentPhase+1&&(!CT.focusedRoute?.enabled()||!options.cert||row.topic.certs.includes(options.cert.id))).sort((a,b)=>b.score-a.score||a.mastery-b.mastery||a.phase-b.phase||a.topic.title.localeCompare(b.topic.title)).slice(0,limit);}
  function next(options={}){return recommend({...options,limit:1})[0]||null;}
  function forPhase(phaseNumber,options={}){return focusedTopics().filter(t=>t.phase===Number(phaseNumber)).map(topic=>score(topic,options)).sort((a,b)=>b.score-a.score||a.mastery-b.mastery).slice(0,Number(options.limit||3));}

  CT.topicEngine=Object.freeze({TOPICS,score,recommend,next,forPhase,mastery});
})(window);
